# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/UI_CAccount.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CASHIER_ACCOUNT(object):
    def setupUi(self, CASHIER_ACCOUNT):
        CASHIER_ACCOUNT.setObjectName("CASHIER_ACCOUNT")
        CASHIER_ACCOUNT.resize(1936, 1005)
        CASHIER_ACCOUNT.setStyleSheet("background: white;")
        self.frame = QtWidgets.QFrame(CASHIER_ACCOUNT)
        self.frame.setGeometry(QtCore.QRect(299, 209, 1621, 791))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.stackedWidget_AccountBtns = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget_AccountBtns.setEnabled(True)
        self.stackedWidget_AccountBtns.setGeometry(QtCore.QRect(-1, 69, 1621, 651))
        self.stackedWidget_AccountBtns.setObjectName("stackedWidget_AccountBtns")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame_9 = QtWidgets.QFrame(self.page)
        self.frame_9.setGeometry(QtCore.QRect(590, 0, 1031, 661))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.frame_46 = QtWidgets.QFrame(self.frame_9)
        self.frame_46.setGeometry(QtCore.QRect(0, 0, 981, 661))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.frame_46.setFont(font)
        self.frame_46.setStyleSheet("background: transparent;")
        self.frame_46.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.cashierIDText = QtWidgets.QLabel(self.frame_46)
        self.cashierIDText.setGeometry(QtCore.QRect(230, 120, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.cashierIDText.setFont(font)
        self.cashierIDText.setStyleSheet("\n"
"QLabel {\n"
"    font-size:36px;\n"
"}\n"
"    \n"
"")
        self.cashierIDText.setObjectName("cashierIDText")
        self.cashierRoleText_2 = QtWidgets.QLabel(self.frame_46)
        self.cashierRoleText_2.setGeometry(QtCore.QRect(230, 260, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.cashierRoleText_2.setFont(font)
        self.cashierRoleText_2.setStyleSheet("\n"
"QLabel {\n"
"    font-size:36px;\n"
"}\n"
"    \n"
"")
        self.cashierRoleText_2.setObjectName("cashierRoleText_2")
        self.cashierNameText_2 = QtWidgets.QLabel(self.frame_46)
        self.cashierNameText_2.setGeometry(QtCore.QRect(230, 380, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.cashierNameText_2.setFont(font)
        self.cashierNameText_2.setStyleSheet("\n"
"QLabel {\n"
"    font-size:36px;\n"
"}\n"
"    \n"
"")
        self.cashierNameText_2.setObjectName("cashierNameText_2")
        self.label_7 = QtWidgets.QLabel(self.frame_46)
        self.label_7.setGeometry(QtCore.QRect(-70, 40, 1051, 501))
        self.label_7.setStyleSheet("background-color: rgba(235, 224, 204, 0.47); \n"
"border-radius: 80px;\n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.cashierID = QtWidgets.QLabel(self.frame_46)
        self.cashierID.setGeometry(QtCore.QRect(220, 170, 561, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        self.cashierID.setFont(font)
        self.cashierID.setStyleSheet("border: 1px solid #000000; \n"
"border-radius: 22px; \n"
"padding: 1px;")
        self.cashierID.setText("")
        self.cashierID.setObjectName("cashierID")
        self.cashierRole = QtWidgets.QLabel(self.frame_46)
        self.cashierRole.setGeometry(QtCore.QRect(220, 300, 561, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        self.cashierRole.setFont(font)
        self.cashierRole.setStyleSheet("border: 1px solid #000000; \n"
"border-radius: 22px; \n"
"padding: 1px;")
        self.cashierRole.setText("")
        self.cashierRole.setObjectName("cashierRole")
        self.cashierName = QtWidgets.QLabel(self.frame_46)
        self.cashierName.setGeometry(QtCore.QRect(220, 420, 561, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        self.cashierName.setFont(font)
        self.cashierName.setStyleSheet("border: 1px solid #000000; \n"
"border-radius: 22px; \n"
"padding: 1px;")
        self.cashierName.setText("")
        self.cashierName.setObjectName("cashierName")
        self.label_7.raise_()
        self.cashierIDText.raise_()
        self.cashierNameText_2.raise_()
        self.cashierRoleText_2.raise_()
        self.cashierID.raise_()
        self.cashierRole.raise_()
        self.cashierName.raise_()
        self.frame_10 = QtWidgets.QFrame(self.page)
        self.frame_10.setGeometry(QtCore.QRect(0, 0, 591, 661))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_createUSER_profile_pic_cashier_3 = QtWidgets.QLabel(self.frame_10)
        self.label_createUSER_profile_pic_cashier_3.setGeometry(QtCore.QRect(150, 80, 400, 400))
        self.label_createUSER_profile_pic_cashier_3.setStyleSheet("border-radius: 200px;   /* half of 400 */\n"
"border: 2px solid #12245c;  /* optional: blue border */\n"
"")
        self.label_createUSER_profile_pic_cashier_3.setText("")
        self.label_createUSER_profile_pic_cashier_3.setPixmap(QtGui.QPixmap("views\\../resources/images/userProfilepicture.png"))
        self.label_createUSER_profile_pic_cashier_3.setScaledContents(True)
        self.label_createUSER_profile_pic_cashier_3.setObjectName("label_createUSER_profile_pic_cashier_3")
        self.label_9 = QtWidgets.QLabel(self.frame_10)
        self.label_9.setGeometry(QtCore.QRect(60, 40, 671, 501))
        self.label_9.setStyleSheet("background-color: rgba(235, 224, 204, 0.47); /* #ebe0cc with 47% opacity */\n"
"border-radius:80px;")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_9.raise_()
        self.label_createUSER_profile_pic_cashier_3.raise_()
        self.stackedWidget_AccountBtns.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget_AccountBtns.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget_AccountBtns.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.frame_7 = QtWidgets.QFrame(self.page_4)
        self.frame_7.setGeometry(QtCore.QRect(590, -10, 1031, 661))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.stackedWidget_AccountBtns.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.stackedWidget_AccountBtns.addWidget(self.page_5)
        self.frame_45 = QtWidgets.QFrame(CASHIER_ACCOUNT)
        self.frame_45.setGeometry(QtCore.QRect(300, 0, 1621, 211))
        self.frame_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.timeLabel = QtWidgets.QLabel(self.frame_45)
        self.timeLabel.setGeometry(QtCore.QRect(840, 20, 731, 171))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.timeLabel.setFont(font)
        self.timeLabel.setStyleSheet("\n"
"    background-color: #f6f3ee;\n"
"    border-radius: 16;\n"
"    padding: 10px;\n"
"color: #051a54;\n"
"")
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.dateLabel = QtWidgets.QLabel(self.frame_45)
        self.dateLabel.setGeometry(QtCore.QRect(40, 20, 771, 171))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setBold(True)
        font.setWeight(75)
        self.dateLabel.setFont(font)
        self.dateLabel.setStyleSheet("\n"
"    background-color: #f6f3ee;\n"
"    border-radius: 16;\n"
"    padding: 10px;\n"
"\n"
"")
        self.dateLabel.setTextFormat(QtCore.Qt.RichText)
        self.dateLabel.setObjectName("dateLabel")
        self.label = QtWidgets.QLabel(CASHIER_ACCOUNT)
        self.label.setGeometry(QtCore.QRect(300, 930, 1631, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: #374550;\n"
"padding: 2px;\n"
"color: #ffffff;\n"
"text-align: center;\n"
"")
        self.label.setObjectName("label")
        self.LeftMenuBar = QtWidgets.QFrame(CASHIER_ACCOUNT)
        self.LeftMenuBar.setGeometry(QtCore.QRect(0, 0, 301, 1011))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LeftMenuBar.setFont(font)
        self.LeftMenuBar.setStyleSheet("background-color: rgba(235, 224, 204, 0.47); /* #ebe0cc with 47% opacity */")
        self.LeftMenuBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LeftMenuBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LeftMenuBar.setObjectName("LeftMenuBar")
        self.JJelevate_text_2 = QtWidgets.QLabel(self.LeftMenuBar)
        self.JJelevate_text_2.setGeometry(QtCore.QRect(60, 220, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.JJelevate_text_2.setFont(font)
        self.JJelevate_text_2.setStyleSheet("color: #12245c;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"background: transparent;\n"
"font-size: 30px;")
        self.JJelevate_text_2.setScaledContents(True)
        self.JJelevate_text_2.setObjectName("JJelevate_text_2")
        self.Logo = QtWidgets.QLabel(self.LeftMenuBar)
        self.Logo.setGeometry(QtCore.QRect(30, 50, 241, 171))
        self.Logo.setStyleSheet("background: transparent;")
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("views\\../resources/images/JJLOGO.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setAlignment(QtCore.Qt.AlignCenter)
        self.Logo.setObjectName("Logo")
        self.pushButton_Dashboard = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Dashboard.setGeometry(QtCore.QRect(30, 310, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_Dashboard.setFont(font)
        self.pushButton_Dashboard.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("views\\../resources/images/dashboard_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Dashboard.setIcon(icon)
        self.pushButton_Dashboard.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Dashboard.setObjectName("pushButton_Dashboard")
        self.pushButton_Order_History = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Order_History.setGeometry(QtCore.QRect(30, 470, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Order_History.setFont(font)
        self.pushButton_Order_History.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("views\\../resources/images/inventory_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Order_History.setIcon(icon1)
        self.pushButton_Order_History.setIconSize(QtCore.QSize(46, 42))
        self.pushButton_Order_History.setObjectName("pushButton_Order_History")
        self.pushButton_Sales = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Sales.setGeometry(QtCore.QRect(30, 550, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Sales.setFont(font)
        self.pushButton_Sales.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("views\\../resources/images/sales_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Sales.setIcon(icon2)
        self.pushButton_Sales.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_Sales.setObjectName("pushButton_Sales")
        self.pushButton_Account = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Account.setGeometry(QtCore.QRect(30, 630, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Account.setFont(font)
        self.pushButton_Account.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("views\\../resources/images/account_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Account.setIcon(icon3)
        self.pushButton_Account.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_Account.setObjectName("pushButton_Account")
        self.pushButton_LogOut = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_LogOut.setGeometry(QtCore.QRect(30, 890, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(87)
        self.pushButton_LogOut.setFont(font)
        self.pushButton_LogOut.setStyleSheet("QPushButton {\n"
"    background-color:#022162;\n"
"color:white;\n"
"font-weight: 700;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"font-size: 14;\n"
"text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"        background-color: rgba(2, 33, 98, 0.8);\n"
"        color: white;\n"
"    font-weight: 700;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("views\\../resources/images/WHITElogout_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_LogOut.setIcon(icon4)
        self.pushButton_LogOut.setIconSize(QtCore.QSize(38, 38))
        self.pushButton_LogOut.setObjectName("pushButton_LogOut")
        self.JJelevate_text_3 = QtWidgets.QLabel(self.LeftMenuBar)
        self.JJelevate_text_3.setGeometry(QtCore.QRect(130, 220, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.JJelevate_text_3.setFont(font)
        self.JJelevate_text_3.setStyleSheet("color: #d75413;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"background: transparent;\n"
"font-size: 29px;\n"
"")
        self.JJelevate_text_3.setScaledContents(True)
        self.JJelevate_text_3.setObjectName("JJelevate_text_3")
        self.pushButton_Orders = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Orders.setGeometry(QtCore.QRect(30, 390, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Orders.setFont(font)
        self.pushButton_Orders.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("views\\../resources/images/orders_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Orders.setIcon(icon5)
        self.pushButton_Orders.setIconSize(QtCore.QSize(46, 42))
        self.pushButton_Orders.setObjectName("pushButton_Orders")

        self.retranslateUi(CASHIER_ACCOUNT)
        self.stackedWidget_AccountBtns.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CASHIER_ACCOUNT)

    def retranslateUi(self, CASHIER_ACCOUNT):
        _translate = QtCore.QCoreApplication.translate
        CASHIER_ACCOUNT.setWindowTitle(_translate("CASHIER_ACCOUNT", "Form"))
        self.cashierIDText.setText(_translate("CASHIER_ACCOUNT", "User ID"))
        self.cashierRoleText_2.setText(_translate("CASHIER_ACCOUNT", "User Role"))
        self.cashierNameText_2.setText(_translate("CASHIER_ACCOUNT", "Username"))
        self.timeLabel.setText(_translate("CASHIER_ACCOUNT", " 09 : 10 : 54 AM"))
        self.dateLabel.setText(_translate("CASHIER_ACCOUNT", "<html><head/><body><p align=\"center\"><span style=\" font-size:38pt; color:#022162;\">March 1, 2025</span><br/><span style=\" font-size:20pt; color:#b2423c;\">Monday</span></p></body></html>"))
        self.label.setText(_translate("CASHIER_ACCOUNT", "                                                                           J  &  J  ROOFSTEEL  AND  GUTTER  SUPPLY  (MOALBOAL BRANCH)     "))
        self.JJelevate_text_2.setText(_translate("CASHIER_ACCOUNT", "J&J "))
        self.pushButton_Dashboard.setText(_translate("CASHIER_ACCOUNT", "  Home   "))
        self.pushButton_Order_History.setText(_translate("CASHIER_ACCOUNT", "Order History"))
        self.pushButton_Sales.setText(_translate("CASHIER_ACCOUNT", "  Sales"))
        self.pushButton_Account.setText(_translate("CASHIER_ACCOUNT", " Account     "))
        self.pushButton_LogOut.setText(_translate("CASHIER_ACCOUNT", "   Log out"))
        self.JJelevate_text_3.setText(_translate("CASHIER_ACCOUNT", "Elevate"))
        self.pushButton_Orders.setText(_translate("CASHIER_ACCOUNT", " Orders"))
