# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/UI_COrders.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CASHIER_ORDERS(object):
    def setupUi(self, CASHIER_ORDERS):
        CASHIER_ORDERS.setObjectName("CASHIER_ORDERS")
        CASHIER_ORDERS.resize(1933, 1005)
        CASHIER_ORDERS.setStyleSheet("background: white;")
        self.LeftMenuBar = QtWidgets.QFrame(CASHIER_ORDERS)
        self.LeftMenuBar.setGeometry(QtCore.QRect(0, 0, 301, 1011))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LeftMenuBar.setFont(font)
        self.LeftMenuBar.setStyleSheet("background-color: rgba(235, 224, 204, 0.47); /* #ebe0cc with 47% opacity */")
        self.LeftMenuBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LeftMenuBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LeftMenuBar.setObjectName("LeftMenuBar")
        self.JJelevate_text_2 = QtWidgets.QLabel(self.LeftMenuBar)
        self.JJelevate_text_2.setGeometry(QtCore.QRect(60, 220, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.JJelevate_text_2.setFont(font)
        self.JJelevate_text_2.setStyleSheet("color: #12245c;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"background: transparent;\n"
"font-size: 30px;")
        self.JJelevate_text_2.setScaledContents(True)
        self.JJelevate_text_2.setObjectName("JJelevate_text_2")
        self.Logo = QtWidgets.QLabel(self.LeftMenuBar)
        self.Logo.setGeometry(QtCore.QRect(30, 50, 241, 171))
        self.Logo.setStyleSheet("background: transparent;")
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("views\\../../Cashier UI/JJ-ELEVATE-Final-Project-main/ui/resources/images/JJLOGO.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setAlignment(QtCore.Qt.AlignCenter)
        self.Logo.setObjectName("Logo")
        self.pushButton_Dashboard = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Dashboard.setGeometry(QtCore.QRect(30, 310, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_Dashboard.setFont(font)
        self.pushButton_Dashboard.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("views\\../../Cashier UI/JJ-ELEVATE-Final-Project-main/ui/resources/images/dashboard_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Dashboard.setIcon(icon)
        self.pushButton_Dashboard.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Dashboard.setObjectName("pushButton_Dashboard")
        self.pushButton_Order_History = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Order_History.setGeometry(QtCore.QRect(30, 470, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Order_History.setFont(font)
        self.pushButton_Order_History.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("views\\../../Cashier UI/JJ-ELEVATE-Final-Project-main/ui/resources/images/inventory_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Order_History.setIcon(icon1)
        self.pushButton_Order_History.setIconSize(QtCore.QSize(46, 42))
        self.pushButton_Order_History.setObjectName("pushButton_Order_History")
        self.pushButton_Sales = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Sales.setGeometry(QtCore.QRect(30, 550, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Sales.setFont(font)
        self.pushButton_Sales.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("views\\../../Cashier UI/JJ-ELEVATE-Final-Project-main/ui/resources/images/sales_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Sales.setIcon(icon2)
        self.pushButton_Sales.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_Sales.setObjectName("pushButton_Sales")
        self.pushButton_Account = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Account.setGeometry(QtCore.QRect(30, 630, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Account.setFont(font)
        self.pushButton_Account.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("views\\../../Cashier UI/JJ-ELEVATE-Final-Project-main/ui/resources/images/account_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Account.setIcon(icon3)
        self.pushButton_Account.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_Account.setObjectName("pushButton_Account")
        self.pushButton_LogOut = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_LogOut.setGeometry(QtCore.QRect(30, 890, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(87)
        self.pushButton_LogOut.setFont(font)
        self.pushButton_LogOut.setStyleSheet("QPushButton {\n"
"    background-color:#022162;\n"
"color:white;\n"
"font-weight: 700;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"font-size: 14;\n"
"text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"        background-color: rgba(2, 33, 98, 0.8);\n"
"        color: white;\n"
"    font-weight: 700;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("views\\../../Cashier UI/JJ-ELEVATE-Final-Project-main/ui/resources/images/WHITElogout_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_LogOut.setIcon(icon4)
        self.pushButton_LogOut.setIconSize(QtCore.QSize(38, 38))
        self.pushButton_LogOut.setObjectName("pushButton_LogOut")
        self.JJelevate_text_3 = QtWidgets.QLabel(self.LeftMenuBar)
        self.JJelevate_text_3.setGeometry(QtCore.QRect(130, 220, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.JJelevate_text_3.setFont(font)
        self.JJelevate_text_3.setStyleSheet("color: #d75413;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"background: transparent;\n"
"font-size: 29px;\n"
"")
        self.JJelevate_text_3.setScaledContents(True)
        self.JJelevate_text_3.setObjectName("JJelevate_text_3")
        self.pushButton_Orders = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Orders.setGeometry(QtCore.QRect(30, 390, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Orders.setFont(font)
        self.pushButton_Orders.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("views\\../../Cashier UI/JJ-ELEVATE-Final-Project-main/ui/resources/images/orders_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Orders.setIcon(icon5)
        self.pushButton_Orders.setIconSize(QtCore.QSize(46, 42))
        self.pushButton_Orders.setObjectName("pushButton_Orders")
        self.stackedWidget_Orders = QtWidgets.QStackedWidget(CASHIER_ORDERS)
        self.stackedWidget_Orders.setGeometry(QtCore.QRect(299, -1, 1631, 1001))
        self.stackedWidget_Orders.setObjectName("stackedWidget_Orders")
        self.Product_List = QtWidgets.QWidget()
        self.Product_List.setObjectName("Product_List")
        self.frame_45 = QtWidgets.QFrame(self.Product_List)
        self.frame_45.setGeometry(QtCore.QRect(0, 0, 1601, 151))
        self.frame_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.comboBox_filterProduct_List = QtWidgets.QComboBox(self.frame_45)
        self.comboBox_filterProduct_List.setGeometry(QtCore.QRect(1330, 50, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.comboBox_filterProduct_List.setFont(font)
        self.comboBox_filterProduct_List.setStyleSheet("    background-color: #ebe0cc;\n"
"    border-radius: 15px;\n"
"font-size:28px;\n"
"text-align: center;")
        self.comboBox_filterProduct_List.setObjectName("comboBox_filterProduct_List")
        self.comboBox_filterProduct_List.addItem("")
        self.comboBox_filterProduct_List.addItem("")
        self.comboBox_filterProduct_List.addItem("")
        self.comboBox_filterProduct_List.addItem("")
        self.comboBox_filterProduct_List.addItem("")
        self.frame_4 = QtWidgets.QFrame(self.frame_45)
        self.frame_4.setGeometry(QtCore.QRect(810, 50, 511, 71))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.lineEdit__QuicksearchProduct = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit__QuicksearchProduct.setGeometry(QtCore.QRect(10, 10, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit__QuicksearchProduct.setFont(font)
        self.lineEdit__QuicksearchProduct.setStyleSheet("\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    padding: 2px;\n"
"    text-align: center;\n"
"\n"
"\n"
"\n"
"")
        self.lineEdit__QuicksearchProduct.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit__QuicksearchProduct.setClearButtonEnabled(False)
        self.lineEdit__QuicksearchProduct.setObjectName("lineEdit__QuicksearchProduct")
        self.label_18 = QtWidgets.QLabel(self.frame_4)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 71, 51))
        self.label_18.setStyleSheet("background: transparent;\n"
"padding: 5;\n"
"")
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("views\\../../Cashier UI/JJ-ELEVATE-Final-Project-main/ui/resources/images/search.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.pushButton_searchProduct = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_searchProduct.setGeometry(QtCore.QRect(300, 10, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_searchProduct.setFont(font)
        self.pushButton_searchProduct.setStyleSheet("    QPushButton {\n"
"        background-color: #003366;\n"
"        color: white;\n"
"        padding: 2px;\n"
"        text-align: center;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgba(0, 51, 102, 0.9);\n"
"    }")
        self.pushButton_searchProduct.setObjectName("pushButton_searchProduct")
        self.orderReportText = QtWidgets.QLabel(self.frame_45)
        self.orderReportText.setGeometry(QtCore.QRect(50, 50, 761, 71))
        self.orderReportText.setStyleSheet("color: #12245c;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"background: transparent;\n"
"font-size: 50px;")
        self.orderReportText.setObjectName("orderReportText")
        self.frame = QtWidgets.QFrame(self.Product_List)
        self.frame.setGeometry(QtCore.QRect(-1, 149, 1621, 501))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_12 = QtWidgets.QFrame(self.frame)
        self.frame_12.setGeometry(QtCore.QRect(40, 0, 1531, 71))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.pushButton_Inventory_ALL_ITEMS_table = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_Inventory_ALL_ITEMS_table.setGeometry(QtCore.QRect(0, 10, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        self.pushButton_Inventory_ALL_ITEMS_table.setFont(font)
        self.pushButton_Inventory_ALL_ITEMS_table.setStyleSheet("/* Default Inactive Buttons */\n"
"QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: black;\n"
"    border: 1px solid #004aad; \n"
"    padding: 10px;\n"
"    font-family: \"Verdana\", sans-serif; \n"
"    text-align: center;\n"
"    border-top-left-radius: 12px;\n"
"    border-top-right-radius: 12px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color: #903929;\n"
"    color: white;\n"
"    font-weight: 700;\n"
"    border: 1px solid #903929; \n"
"}\n"
"\n"
"/* Active Table View Button */\n"
"QPushButton.activeButton {\n"
"    background-color: #903929;\n"
"    color: white;\n"
"    font-weight: 700;\n"
"    border: 1px solid #903929;\n"
"}\n"
"\n"
"/* Active Action Button (Add/Edit/Delete) */\n"
"QPushButton.activeActionButton {\n"
"    background-color: #c25b55;\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"    padding: 2px;\n"
"}")
        self.pushButton_Inventory_ALL_ITEMS_table.setObjectName("pushButton_Inventory_ALL_ITEMS_table")
        self.pushButton_Inventory_ROOF_table = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_Inventory_ROOF_table.setGeometry(QtCore.QRect(300, 10, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        self.pushButton_Inventory_ROOF_table.setFont(font)
        self.pushButton_Inventory_ROOF_table.setStyleSheet("/* Default Inactive Buttons */\n"
"QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: black;\n"
"    border: 1px solid #004aad; \n"
"    padding: 10px;\n"
"    font-family: \"Verdana\", sans-serif; \n"
"    text-align: center;\n"
"    border-top-left-radius: 12px;\n"
"    border-top-right-radius: 12px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color: #903929;\n"
"    color: white;\n"
"    font-weight: 700;\n"
"    border: 1px solid #903929; \n"
"}\n"
"\n"
"/* Active Table View Button */\n"
"QPushButton.activeButton {\n"
"    background-color: #903929;\n"
"    color: white;\n"
"    font-weight: 700;\n"
"    border: 1px solid #903929;\n"
"}\n"
"\n"
"/* Active Action Button (Add/Edit/Delete) */\n"
"QPushButton.activeActionButton {\n"
"    background-color: #c25b55;\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"    padding: 2px;\n"
"}")
        self.pushButton_Inventory_ROOF_table.setObjectName("pushButton_Inventory_ROOF_table")
        self.pushButton_Inventory_SPANDREL_table = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_Inventory_SPANDREL_table.setGeometry(QtCore.QRect(600, 10, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        self.pushButton_Inventory_SPANDREL_table.setFont(font)
        self.pushButton_Inventory_SPANDREL_table.setStyleSheet("/* Default Inactive Buttons */\n"
"QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: black;\n"
"    border: 1px solid #004aad; \n"
"    padding: 10px;\n"
"    font-family: \"Verdana\", sans-serif; \n"
"    text-align: center;\n"
"    border-top-left-radius: 12px;\n"
"    border-top-right-radius: 12px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color: #903929;\n"
"    color: white;\n"
"    font-weight: 700;\n"
"    border: 1px solid #903929; \n"
"}\n"
"\n"
"/* Active Table View Button */\n"
"QPushButton.activeButton {\n"
"    background-color: #903929;\n"
"    color: white;\n"
"    font-weight: 700;\n"
"    border: 1px solid #903929;\n"
"}\n"
"\n"
"/* Active Action Button (Add/Edit/Delete) */\n"
"QPushButton.activeActionButton {\n"
"    background-color: #c25b55;\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"    padding: 2px;\n"
"}")
        self.pushButton_Inventory_SPANDREL_table.setObjectName("pushButton_Inventory_SPANDREL_table")
        self.pushButton_Inventory_GUTTER_table = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_Inventory_GUTTER_table.setGeometry(QtCore.QRect(910, 10, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        self.pushButton_Inventory_GUTTER_table.setFont(font)
        self.pushButton_Inventory_GUTTER_table.setStyleSheet("/* Default Inactive Buttons */\n"
"QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: black;\n"
"    border: 1px solid #004aad; \n"
"    padding: 10px;\n"
"    font-family: \"Verdana\", sans-serif; \n"
"    text-align: center;\n"
"    border-top-left-radius: 12px;\n"
"    border-top-right-radius: 12px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color: #903929;\n"
"    color: white;\n"
"    font-weight: 700;\n"
"    border: 1px solid #903929; \n"
"}\n"
"\n"
"/* Active Table View Button */\n"
"QPushButton.activeButton {\n"
"    background-color: #903929;\n"
"    color: white;\n"
"    font-weight: 700;\n"
"    border: 1px solid #903929;\n"
"}\n"
"\n"
"/* Active Action Button (Add/Edit/Delete) */\n"
"QPushButton.activeActionButton {\n"
"    background-color: #c25b55;\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"    padding: 2px;\n"
"}")
        self.pushButton_Inventory_GUTTER_table.setObjectName("pushButton_Inventory_GUTTER_table")
        self.pushButton_Inventory_OTHER_table = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_Inventory_OTHER_table.setGeometry(QtCore.QRect(1220, 10, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        self.pushButton_Inventory_OTHER_table.setFont(font)
        self.pushButton_Inventory_OTHER_table.setStyleSheet("/* Default Inactive Buttons */\n"
"QPushButton {\n"
"    background-color: #ffffff;\n"
"    color: black;\n"
"    border: 1px solid #004aad; \n"
"    padding: 10px;\n"
"    font-family: \"Verdana\", sans-serif; \n"
"    text-align: center;\n"
"    border-top-left-radius: 12px;\n"
"    border-top-right-radius: 12px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color: #903929;\n"
"    color: white;\n"
"    font-weight: 700;\n"
"    border: 1px solid #903929; \n"
"}\n"
"\n"
"/* Active Table View Button */\n"
"QPushButton.activeButton {\n"
"    background-color: #903929;\n"
"    color: white;\n"
"    font-weight: 700;\n"
"    border: 1px solid #903929;\n"
"}\n"
"\n"
"/* Active Action Button (Add/Edit/Delete) */\n"
"QPushButton.activeActionButton {\n"
"    background-color: #c25b55;\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"    padding: 2px;\n"
"}")
        self.pushButton_Inventory_OTHER_table.setObjectName("pushButton_Inventory_OTHER_table")
        self.tableWidget_Product_List = QtWidgets.QTableWidget(self.frame)
        self.tableWidget_Product_List.setGeometry(QtCore.QRect(40, 70, 1531, 431))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        self.tableWidget_Product_List.setFont(font)
        self.tableWidget_Product_List.setStyleSheet("QTableWidget {\n"
"    background-color: white;\n"
"    gridline-color: lightgray;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #003366; \n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"padding: 3;\n"
"}\n"
"")
        self.tableWidget_Product_List.setObjectName("tableWidget_Product_List")
        self.tableWidget_Product_List.setColumnCount(5)
        self.tableWidget_Product_List.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_Product_List.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_Product_List.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_Product_List.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_Product_List.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_Product_List.setHorizontalHeaderItem(4, item)
        self.tableWidget_Product_List.horizontalHeader().setDefaultSectionSize(306)
        self.frame_2 = QtWidgets.QFrame(self.Product_List)
        self.frame_2.setGeometry(QtCore.QRect(0, 650, 1621, 351))
        self.frame_2.setStyleSheet("background: transparent;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_46 = QtWidgets.QFrame(self.frame_2)
        self.frame_46.setGeometry(QtCore.QRect(40, 30, 1531, 271))
        self.frame_46.setStyleSheet("\n"
"    background-color: #f6f3ee;\n"
"    border-radius: 16;\n"
"    padding: 10px;\n"
"\n"
"")
        self.frame_46.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.label_644 = QtWidgets.QLabel(self.frame_46)
        self.label_644.setGeometry(QtCore.QRect(30, 70, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_644.setFont(font)
        self.label_644.setStyleSheet("    background-color: transparent;\n"
"")
        self.label_644.setObjectName("label_644")
        self.pushButton_Save_OTHERedit = QtWidgets.QPushButton(self.frame_46)
        self.pushButton_Save_OTHERedit.setGeometry(QtCore.QRect(0, 0, 1531, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Save_OTHERedit.setFont(font)
        self.pushButton_Save_OTHERedit.setStyleSheet("\n"
"    background-color: #8d2721;\n"
"    color: white;\n"
"    border-radius: 15px;\n"
"    border: 1px solid #000000;\n"
"    padding: 9px;\n"
"    text-align: center;\n"
"\n"
"")
        self.pushButton_Save_OTHERedit.setObjectName("pushButton_Save_OTHERedit")
        self.label_645 = QtWidgets.QLabel(self.frame_46)
        self.label_645.setGeometry(QtCore.QRect(30, 140, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_645.setFont(font)
        self.label_645.setStyleSheet("    background-color: transparent;\n"
"")
        self.label_645.setObjectName("label_645")
        self.OrderInput_Product = QtWidgets.QLineEdit(self.frame_46)
        self.OrderInput_Product.setGeometry(QtCore.QRect(190, 70, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.OrderInput_Product.setFont(font)
        self.OrderInput_Product.setStyleSheet("    background-color: #ffffff;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"border: 1px solid #000000; \n"
"    padding: 9px;\n"
"")
        self.OrderInput_Product.setObjectName("OrderInput_Product")
        self.OrderInput_Thickness = QtWidgets.QLineEdit(self.frame_46)
        self.OrderInput_Thickness.setGeometry(QtCore.QRect(190, 140, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.OrderInput_Thickness.setFont(font)
        self.OrderInput_Thickness.setStyleSheet("    background-color: #ffffff;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"border: 1px solid #000000; \n"
"    padding: 9px;\n"
"")
        self.OrderInput_Thickness.setObjectName("OrderInput_Thickness")
        self.label_646 = QtWidgets.QLabel(self.frame_46)
        self.label_646.setGeometry(QtCore.QRect(570, 70, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_646.setFont(font)
        self.label_646.setStyleSheet("    background-color: transparent;\n"
"")
        self.label_646.setObjectName("label_646")
        self.OrderInput_Width = QtWidgets.QLineEdit(self.frame_46)
        self.OrderInput_Width.setGeometry(QtCore.QRect(700, 70, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.OrderInput_Width.setFont(font)
        self.OrderInput_Width.setStyleSheet("    background-color: #ffffff;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"border: 1px solid #000000; \n"
"    padding: 9px;\n"
"")
        self.OrderInput_Width.setObjectName("OrderInput_Width")
        self.OrderInput_Length = QtWidgets.QLineEdit(self.frame_46)
        self.OrderInput_Length.setGeometry(QtCore.QRect(1210, 70, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.OrderInput_Length.setFont(font)
        self.OrderInput_Length.setStyleSheet("    background-color: #ffffff;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"border: 1px solid #000000; \n"
"    padding: 9px;\n"
"")
        self.OrderInput_Length.setObjectName("OrderInput_Length")
        self.label_647 = QtWidgets.QLabel(self.frame_46)
        self.label_647.setGeometry(QtCore.QRect(1070, 70, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_647.setFont(font)
        self.label_647.setStyleSheet("    background-color: transparent;\n"
"")
        self.label_647.setObjectName("label_647")
        self.label_648 = QtWidgets.QLabel(self.frame_46)
        self.label_648.setGeometry(QtCore.QRect(570, 140, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_648.setFont(font)
        self.label_648.setStyleSheet("    background-color: transparent;\n"
"")
        self.label_648.setObjectName("label_648")
        self.OrderInput_Height = QtWidgets.QLineEdit(self.frame_46)
        self.OrderInput_Height.setGeometry(QtCore.QRect(700, 140, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.OrderInput_Height.setFont(font)
        self.OrderInput_Height.setStyleSheet("    background-color: #ffffff;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"border: 1px solid #000000; \n"
"    padding: 9px;\n"
"")
        self.OrderInput_Height.setObjectName("OrderInput_Height")
        self.label_649 = QtWidgets.QLabel(self.frame_46)
        self.label_649.setGeometry(QtCore.QRect(1070, 140, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_649.setFont(font)
        self.label_649.setStyleSheet("    background-color: transparent;\n"
"")
        self.label_649.setObjectName("label_649")
        self.OrderInput_Color = QtWidgets.QLineEdit(self.frame_46)
        self.OrderInput_Color.setGeometry(QtCore.QRect(1210, 140, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.OrderInput_Color.setFont(font)
        self.OrderInput_Color.setStyleSheet("    background-color: #ffffff;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"border: 1px solid #000000; \n"
"    padding: 9px;\n"
"")
        self.OrderInput_Color.setObjectName("OrderInput_Color")
        self.Add_Order = QtWidgets.QPushButton(self.frame_46)
        self.Add_Order.setGeometry(QtCore.QRect(1360, 210, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Add_Order.setFont(font)
        self.Add_Order.setStyleSheet("/* Default Inactive Button */\n"
"QPushButton {\n"
"    background-color: #003366;\n"
"    color: #fefefe;\n"
"    border-radius: 15px;\n"
"    padding: 9px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 51, 102, 0.9); /* 90% opacity of #003366 */\n"
"}")
        self.Add_Order.setObjectName("Add_Order")
        self.Cancel_Order = QtWidgets.QPushButton(self.frame_46)
        self.Cancel_Order.setGeometry(QtCore.QRect(1210, 210, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Cancel_Order.setFont(font)
        self.Cancel_Order.setStyleSheet("/* Default Inactive Button */\n"
"QPushButton {\n"
"    background-color: #c25b55;\n"
"    color: #fefefe;\n"
"    border-radius: 15px;\n"
"    padding: 9px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color: rgba(194, 91, 85, 0.9); /* 90% opacity of #c25b55 */\n"
"}")
        self.Cancel_Order.setObjectName("Cancel_Order")
        self.stackedWidget_Orders.addWidget(self.Product_List)
        self.Order_Summary = QtWidgets.QWidget()
        self.Order_Summary.setObjectName("Order_Summary")
        self.label = QtWidgets.QLabel(self.Order_Summary)
        self.label.setGeometry(QtCore.QRect(40, 20, 1531, 951))
        self.label.setStyleSheet("\n"
"    background-color: #f6f3ee;\n"
"    border-radius: 16;\n"
"\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_Save_OTHERedit_2 = QtWidgets.QPushButton(self.Order_Summary)
        self.pushButton_Save_OTHERedit_2.setGeometry(QtCore.QRect(70, 60, 1471, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Save_OTHERedit_2.setFont(font)
        self.pushButton_Save_OTHERedit_2.setStyleSheet("background-color: #8d2721;\n"
"color: white;\n"
"border-top-left-radius: 15px;\n"
"border-top-right-radius: 15px;\n"
"border-bottom-left-radius: 0;\n"
"border-bottom-right-radius: 0;\n"
"border: 1px solid #000000;\n"
"padding: 9px;\n"
"text-align: center;")
        self.pushButton_Save_OTHERedit_2.setObjectName("pushButton_Save_OTHERedit_2")
        self.tableWidget_OrderSummary = QtWidgets.QTableWidget(self.Order_Summary)
        self.tableWidget_OrderSummary.setGeometry(QtCore.QRect(70, 110, 1471, 491))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        self.tableWidget_OrderSummary.setFont(font)
        self.tableWidget_OrderSummary.setStyleSheet("QTableWidget {\n"
"    background-color: white;\n"
"    gridline-color: lightgray;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #003366; \n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"padding: 3;\n"
"}\n"
"")
        self.tableWidget_OrderSummary.setObjectName("tableWidget_OrderSummary")
        self.tableWidget_OrderSummary.setColumnCount(7)
        self.tableWidget_OrderSummary.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_OrderSummary.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_OrderSummary.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_OrderSummary.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_OrderSummary.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_OrderSummary.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_OrderSummary.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_OrderSummary.setHorizontalHeaderItem(6, item)
        self.tableWidget_OrderSummary.horizontalHeader().setDefaultSectionSize(306)
        self.frame_47 = QtWidgets.QFrame(self.Order_Summary)
        self.frame_47.setGeometry(QtCore.QRect(40, 650, 1531, 281))
        self.frame_47.setStyleSheet("\n"
"background: transparent;\n"
"    border-radius: 16;\n"
"    padding: 10px;\n"
"\n"
"")
        self.frame_47.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_47.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_47.setObjectName("frame_47")
        self.label_650 = QtWidgets.QLabel(self.frame_47)
        self.label_650.setGeometry(QtCore.QRect(20, 70, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_650.setFont(font)
        self.label_650.setStyleSheet("    background-color: transparent;\n"
"")
        self.label_650.setObjectName("label_650")
        self.label_651 = QtWidgets.QLabel(self.frame_47)
        self.label_651.setGeometry(QtCore.QRect(20, 140, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_651.setFont(font)
        self.label_651.setStyleSheet("    background-color: transparent;\n"
"")
        self.label_651.setObjectName("label_651")
        self.OrderSummary_CusName = QtWidgets.QLineEdit(self.frame_47)
        self.OrderSummary_CusName.setGeometry(QtCore.QRect(250, 70, 681, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.OrderSummary_CusName.setFont(font)
        self.OrderSummary_CusName.setStyleSheet("    background-color: #ffffff;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"border: 1px solid #000000; \n"
"    padding: 9px;\n"
"")
        self.OrderSummary_CusName.setObjectName("OrderSummary_CusName")
        self.OrderSummary_CusAddress = QtWidgets.QLineEdit(self.frame_47)
        self.OrderSummary_CusAddress.setGeometry(QtCore.QRect(250, 140, 681, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.OrderSummary_CusAddress.setFont(font)
        self.OrderSummary_CusAddress.setStyleSheet("    background-color: #ffffff;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"border: 1px solid #000000; \n"
"    padding: 9px;\n"
"")
        self.OrderSummary_CusAddress.setObjectName("OrderSummary_CusAddress")
        self.pushButton_Save_OTHERedit_3 = QtWidgets.QPushButton(self.frame_47)
        self.pushButton_Save_OTHERedit_3.setGeometry(QtCore.QRect(520, 0, 501, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Save_OTHERedit_3.setFont(font)
        self.pushButton_Save_OTHERedit_3.setStyleSheet("\n"
"    background-color: #8d2721;\n"
"    color: white;\n"
"    border-radius: 15px;\n"
"    border: 1px solid #000000;\n"
"    padding: 9px;\n"
"    text-align: center;\n"
"\n"
"")
        self.pushButton_Save_OTHERedit_3.setObjectName("pushButton_Save_OTHERedit_3")
        self.label_653 = QtWidgets.QLabel(self.frame_47)
        self.label_653.setGeometry(QtCore.QRect(980, 140, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_653.setFont(font)
        self.label_653.setStyleSheet("    background-color: transparent;\n"
"")
        self.label_653.setObjectName("label_653")
        self.label_654 = QtWidgets.QLabel(self.frame_47)
        self.label_654.setGeometry(QtCore.QRect(980, 70, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_654.setFont(font)
        self.label_654.setStyleSheet("    background-color: transparent;\n"
"")
        self.label_654.setObjectName("label_654")
        self.OrderSummary_CusContactnum = QtWidgets.QLineEdit(self.frame_47)
        self.OrderSummary_CusContactnum.setGeometry(QtCore.QRect(1140, 70, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.OrderSummary_CusContactnum.setFont(font)
        self.OrderSummary_CusContactnum.setStyleSheet("    background-color: #ffffff;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"border: 1px solid #000000; \n"
"    padding: 9px;\n"
"")
        self.OrderSummary_CusContactnum.setObjectName("OrderSummary_CusContactnum")
        self.OrderSummary_CusService_type = QtWidgets.QComboBox(self.frame_47)
        self.OrderSummary_CusService_type.setGeometry(QtCore.QRect(1140, 140, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.OrderSummary_CusService_type.setFont(font)
        self.OrderSummary_CusService_type.setStyleSheet("    background-color: #a6a6a6;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"border: 1px solid #000000; \n"
"    padding: 9px;\n"
"")
        self.OrderSummary_CusService_type.setObjectName("OrderSummary_CusService_type")
        self.OrderSummary_CusService_type.addItem("")
        self.OrderSummary_CusService_type.addItem("")
        self.OrderSummary_CusService_type.addItem("")
        self.OrderSummary_CusService_type.addItem("")
        self.dotline_1 = QtWidgets.QLabel(self.frame_47)
        self.dotline_1.setGeometry(QtCore.QRect(0, -30, 521, 251))
        self.dotline_1.setStyleSheet("background: transparent;")
        self.dotline_1.setText("")
        self.dotline_1.setPixmap(QtGui.QPixmap("views\\../../Cashier UI/JJ-ELEVATE-Final-Project-main/ui/resources/images/dottedline.png"))
        self.dotline_1.setScaledContents(True)
        self.dotline_1.setObjectName("dotline_1")
        self.dotline_2 = QtWidgets.QLabel(self.frame_47)
        self.dotline_2.setGeometry(QtCore.QRect(1020, -30, 511, 251))
        self.dotline_2.setStyleSheet("background: transparent;")
        self.dotline_2.setText("")
        self.dotline_2.setPixmap(QtGui.QPixmap("views\\../../Cashier UI/JJ-ELEVATE-Final-Project-main/ui/resources/images/dottedline.png"))
        self.dotline_2.setScaledContents(True)
        self.dotline_2.setObjectName("dotline_2")
        self.OrderSummary_cancelOrder = QtWidgets.QPushButton(self.frame_47)
        self.OrderSummary_cancelOrder.setGeometry(QtCore.QRect(30, 210, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.OrderSummary_cancelOrder.setFont(font)
        self.OrderSummary_cancelOrder.setStyleSheet("/* Default Inactive Button */\n"
"QPushButton {\n"
"    background-color: #c25b55;\n"
"    color: #fefefe;\n"
"    border-radius: 15px;\n"
"    padding: 9px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color: rgba(194, 91, 85, 0.9); /* 90% opacity of #c25b55 */\n"
"}")
        self.OrderSummary_cancelOrder.setObjectName("OrderSummary_cancelOrder")
        self.OrderSummary_submitOrder = QtWidgets.QPushButton(self.frame_47)
        self.OrderSummary_submitOrder.setGeometry(QtCore.QRect(300, 210, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.OrderSummary_submitOrder.setFont(font)
        self.OrderSummary_submitOrder.setStyleSheet("/* Default Inactive Button */\n"
"QPushButton {\n"
"    background-color: #003366;\n"
"    color: #fefefe;\n"
"    border-radius: 15px;\n"
"    padding: 9px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 51, 102, 0.9); /* 90% opacity of #003366 */\n"
"}")
        self.OrderSummary_submitOrder.setObjectName("OrderSummary_submitOrder")
        self.label_650.raise_()
        self.label_651.raise_()
        self.pushButton_Save_OTHERedit_3.raise_()
        self.label_653.raise_()
        self.label_654.raise_()
        self.dotline_1.raise_()
        self.OrderSummary_CusName.raise_()
        self.OrderSummary_CusAddress.raise_()
        self.dotline_2.raise_()
        self.OrderSummary_CusContactnum.raise_()
        self.OrderSummary_CusService_type.raise_()
        self.OrderSummary_cancelOrder.raise_()
        self.OrderSummary_submitOrder.raise_()
        self.stackedWidget_Orders.addWidget(self.Order_Summary)
        self.Receipts = QtWidgets.QWidget()
        self.Receipts.setObjectName("Receipts")
        self.frame_49 = QtWidgets.QFrame(self.Receipts)
        self.frame_49.setGeometry(QtCore.QRect(370, 90, 871, 881))
        self.frame_49.setStyleSheet("\n"
"    background-color: #f6f3ee;\n"
"    border-radius: 16;\n"
"    padding: 10px;\n"
"\n"
"")
        self.frame_49.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_49.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_49.setObjectName("frame_49")
        self.Save_Receipt = QtWidgets.QPushButton(self.frame_49)
        self.Save_Receipt.setGeometry(QtCore.QRect(30, 810, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Save_Receipt.setFont(font)
        self.Save_Receipt.setStyleSheet("/* Default Inactive Button */\n"
"QPushButton {\n"
"    background-color: #c25b55;\n"
"    color: #fefefe;\n"
"    border-radius: 15px;\n"
"    padding: 9px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color: rgba(194, 91, 85, 0.9); /* 90% opacity of #c25b55 */\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("views\\../../Cashier UI/JJ-ELEVATE-Final-Project-main/ui/resources/images/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Save_Receipt.setIcon(icon6)
        self.Save_Receipt.setIconSize(QtCore.QSize(30, 30))
        self.Save_Receipt.setObjectName("Save_Receipt")
        self.Close = QtWidgets.QPushButton(self.frame_49)
        self.Close.setGeometry(QtCore.QRect(310, 810, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Close.setFont(font)
        self.Close.setStyleSheet("/* Default Inactive Button */\n"
"QPushButton {\n"
"    background-color: #a6a6a6;\n"
"    color: #fefefe;\n"
"    border-radius: 15px;\n"
"    padding: 9px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Hover Effect on Inactive Buttons (90% opacity) */\n"
"QPushButton:hover {\n"
"    background-color: rgba(166, 166, 166, 0.9);\n"
"}")
        self.Close.setIconSize(QtCore.QSize(30, 30))
        self.Close.setObjectName("Close")
        self.frame_3 = QtWidgets.QFrame(self.frame_49)
        self.frame_3.setGeometry(QtCore.QRect(40, 500, 241, 311))
        self.frame_3.setStyleSheet("background: transparent;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_655 = QtWidgets.QLabel(self.frame_3)
        self.label_655.setGeometry(QtCore.QRect(0, 250, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_655.setFont(font)
        self.label_655.setStyleSheet("    background-color: transparent;\n"
"")
        self.label_655.setObjectName("label_655")
        self.label_652 = QtWidgets.QLabel(self.frame_3)
        self.label_652.setGeometry(QtCore.QRect(0, 210, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_652.setFont(font)
        self.label_652.setStyleSheet("    background-color: transparent;\n"
"")
        self.label_652.setObjectName("label_652")
        self.label_657 = QtWidgets.QLabel(self.frame_3)
        self.label_657.setGeometry(QtCore.QRect(0, 170, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_657.setFont(font)
        self.label_657.setStyleSheet("    background-color: transparent;\n"
"")
        self.label_657.setObjectName("label_657")
        self.label_658 = QtWidgets.QLabel(self.frame_3)
        self.label_658.setGeometry(QtCore.QRect(0, 130, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_658.setFont(font)
        self.label_658.setStyleSheet("    background-color: transparent;\n"
"")
        self.label_658.setObjectName("label_658")
        self.label_659 = QtWidgets.QLabel(self.frame_3)
        self.label_659.setGeometry(QtCore.QRect(0, 90, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_659.setFont(font)
        self.label_659.setStyleSheet("    background-color: transparent;\n"
"")
        self.label_659.setObjectName("label_659")
        self.label_660 = QtWidgets.QLabel(self.frame_3)
        self.label_660.setGeometry(QtCore.QRect(0, 50, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_660.setFont(font)
        self.label_660.setStyleSheet("    background-color: transparent;\n"
"")
        self.label_660.setObjectName("label_660")
        self.label_661 = QtWidgets.QLabel(self.frame_3)
        self.label_661.setGeometry(QtCore.QRect(0, 10, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_661.setFont(font)
        self.label_661.setStyleSheet("    background-color: transparent;\n"
"")
        self.label_661.setObjectName("label_661")
        self.frame_5 = QtWidgets.QFrame(self.frame_49)
        self.frame_5.setGeometry(QtCore.QRect(280, 500, 591, 311))
        self.frame_5.setStyleSheet("background: transparent;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.storeRcpt_ServiceType = QtWidgets.QLabel(self.frame_5)
        self.storeRcpt_ServiceType.setGeometry(QtCore.QRect(10, 260, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.storeRcpt_ServiceType.setFont(font)
        self.storeRcpt_ServiceType.setStyleSheet("background-color: rgba(255, 255, 255, 0.9); /* #ffffff at 90% opacity */\n"
"color: black;\n"
"border-radius: 15px;\n"
"padding: 9px;")
        self.storeRcpt_ServiceType.setText("")
        self.storeRcpt_ServiceType.setObjectName("storeRcpt_ServiceType")
        self.storeRcpt_CusAddress = QtWidgets.QLabel(self.frame_5)
        self.storeRcpt_CusAddress.setGeometry(QtCore.QRect(10, 220, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.storeRcpt_CusAddress.setFont(font)
        self.storeRcpt_CusAddress.setStyleSheet("background-color: rgba(255, 255, 255, 0.9); /* #ffffff at 90% opacity */\n"
"color: black;\n"
"border-radius: 15px;\n"
"padding: 9px;")
        self.storeRcpt_CusAddress.setText("")
        self.storeRcpt_CusAddress.setObjectName("storeRcpt_CusAddress")
        self.storeRcpt_CusContactnum = QtWidgets.QLabel(self.frame_5)
        self.storeRcpt_CusContactnum.setGeometry(QtCore.QRect(10, 180, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.storeRcpt_CusContactnum.setFont(font)
        self.storeRcpt_CusContactnum.setStyleSheet("background-color: rgba(255, 255, 255, 0.9); /* #ffffff at 90% opacity */\n"
"color: black;\n"
"border-radius: 15px;\n"
"padding: 9px;")
        self.storeRcpt_CusContactnum.setText("")
        self.storeRcpt_CusContactnum.setObjectName("storeRcpt_CusContactnum")
        self.storeRcpt_CusName = QtWidgets.QLabel(self.frame_5)
        self.storeRcpt_CusName.setGeometry(QtCore.QRect(10, 140, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.storeRcpt_CusName.setFont(font)
        self.storeRcpt_CusName.setStyleSheet("background-color: rgba(255, 255, 255, 0.9); /* #ffffff at 90% opacity */\n"
"color: black;\n"
"border-radius: 15px;\n"
"padding: 9px;")
        self.storeRcpt_CusName.setText("")
        self.storeRcpt_CusName.setObjectName("storeRcpt_CusName")
        self.storeRcpt_CashierName = QtWidgets.QLabel(self.frame_5)
        self.storeRcpt_CashierName.setGeometry(QtCore.QRect(10, 100, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.storeRcpt_CashierName.setFont(font)
        self.storeRcpt_CashierName.setStyleSheet("background-color: rgba(255, 255, 255, 0.9); /* #ffffff at 90% opacity */\n"
"color: black;\n"
"border-radius: 15px;\n"
"padding: 9px;")
        self.storeRcpt_CashierName.setText("")
        self.storeRcpt_CashierName.setObjectName("storeRcpt_CashierName")
        self.storeRcpt_DateTime = QtWidgets.QLabel(self.frame_5)
        self.storeRcpt_DateTime.setGeometry(QtCore.QRect(10, 60, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.storeRcpt_DateTime.setFont(font)
        self.storeRcpt_DateTime.setStyleSheet("background-color: rgba(255, 255, 255, 0.9); /* #ffffff at 90% opacity */\n"
"color: black;\n"
"border-radius: 15px;\n"
"padding: 9px;")
        self.storeRcpt_DateTime.setText("")
        self.storeRcpt_DateTime.setObjectName("storeRcpt_DateTime")
        self.storeRcpt_OrderID = QtWidgets.QLabel(self.frame_5)
        self.storeRcpt_OrderID.setGeometry(QtCore.QRect(10, 20, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.storeRcpt_OrderID.setFont(font)
        self.storeRcpt_OrderID.setStyleSheet("background-color: rgba(255, 255, 255, 0.9); /* #ffffff at 90% opacity */\n"
"color: black;\n"
"border-radius: 15px;\n"
"padding: 9px;")
        self.storeRcpt_OrderID.setText("")
        self.storeRcpt_OrderID.setObjectName("storeRcpt_OrderID")
        self.storeRcpt_ReceiptID = QtWidgets.QLabel(self.frame_49)
        self.storeRcpt_ReceiptID.setGeometry(QtCore.QRect(290, 480, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.storeRcpt_ReceiptID.setFont(font)
        self.storeRcpt_ReceiptID.setStyleSheet("background-color: rgba(255, 255, 255, 0.9); /* #ffffff at 90% opacity */\n"
"color: black;\n"
"border-radius: 15px;\n"
"padding: 9px;")
        self.storeRcpt_ReceiptID.setText("")
        self.storeRcpt_ReceiptID.setObjectName("storeRcpt_ReceiptID")
        self.Cancel_Order_5 = QtWidgets.QPushButton(self.frame_49)
        self.Cancel_Order_5.setGeometry(QtCore.QRect(30, 400, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Cancel_Order_5.setFont(font)
        self.Cancel_Order_5.setStyleSheet("    background-color: rgba(0, 51, 102, 0.9); /* 90% opacity of #003366 */\n"
"    color: #fefefe;")
        self.Cancel_Order_5.setIconSize(QtCore.QSize(30, 30))
        self.Cancel_Order_5.setObjectName("Cancel_Order_5")
        self.Cancel_Order_6 = QtWidgets.QPushButton(self.frame_49)
        self.Cancel_Order_6.setGeometry(QtCore.QRect(30, 350, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Cancel_Order_6.setFont(font)
        self.Cancel_Order_6.setStyleSheet("    background-color: rgba(0, 51, 102, 0.9); /* 90% opacity of #003366 */\n"
"    color: #fefefe;")
        self.Cancel_Order_6.setIconSize(QtCore.QSize(30, 30))
        self.Cancel_Order_6.setObjectName("Cancel_Order_6")
        self.label_674 = QtWidgets.QLabel(self.frame_49)
        self.label_674.setGeometry(QtCore.QRect(40, 470, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_674.setFont(font)
        self.label_674.setStyleSheet("    background-color: transparent;\n"
"")
        self.label_674.setObjectName("label_674")
        self.storeRcpt_Total_Price = QtWidgets.QLabel(self.frame_49)
        self.storeRcpt_Total_Price.setGeometry(QtCore.QRect(270, 400, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.storeRcpt_Total_Price.setFont(font)
        self.storeRcpt_Total_Price.setStyleSheet("background-color: rgba(255, 255, 255, 0.9); /* #ffffff at 90% opacity */\n"
"color: black;\n"
"border-radius: 15px;\n"
"padding: 9px;")
        self.storeRcpt_Total_Price.setText("")
        self.storeRcpt_Total_Price.setObjectName("storeRcpt_Total_Price")
        self.storeRcpt_Subtotal_Price = QtWidgets.QLabel(self.frame_49)
        self.storeRcpt_Subtotal_Price.setGeometry(QtCore.QRect(270, 360, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.storeRcpt_Subtotal_Price.setFont(font)
        self.storeRcpt_Subtotal_Price.setStyleSheet("background-color: rgba(255, 255, 255, 0.9); /* #ffffff at 90% opacity */\n"
"color: black;\n"
"border-radius: 15px;\n"
"padding: 9px;")
        self.storeRcpt_Subtotal_Price.setText("")
        self.storeRcpt_Subtotal_Price.setObjectName("storeRcpt_Subtotal_Price")
        self.Cancel_Order_7 = QtWidgets.QPushButton(self.frame_49)
        self.Cancel_Order_7.setGeometry(QtCore.QRect(520, 350, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Cancel_Order_7.setFont(font)
        self.Cancel_Order_7.setStyleSheet("    background-color: rgba(0, 51, 102, 0.9); /* 90% opacity of #003366 */\n"
"    color: #fefefe;")
        self.Cancel_Order_7.setIconSize(QtCore.QSize(30, 30))
        self.Cancel_Order_7.setObjectName("Cancel_Order_7")
        self.storeRcpt_Discount = QtWidgets.QLabel(self.frame_49)
        self.storeRcpt_Discount.setGeometry(QtCore.QRect(700, 360, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.storeRcpt_Discount.setFont(font)
        self.storeRcpt_Discount.setStyleSheet("background-color: rgba(255, 255, 255, 0.9); /* #ffffff at 90% opacity */\n"
"color: black;\n"
"border-radius: 15px;\n"
"padding: 9px;")
        self.storeRcpt_Discount.setText("")
        self.storeRcpt_Discount.setObjectName("storeRcpt_Discount")
        self.tableWidget_storeRcpt = QtWidgets.QTableWidget(self.frame_49)
        self.tableWidget_storeRcpt.setGeometry(QtCore.QRect(20, 41, 831, 301))
        self.tableWidget_storeRcpt.setStyleSheet("padding: 2px;\n"
"backgrouond: transparent;")
        self.tableWidget_storeRcpt.setObjectName("tableWidget_storeRcpt")
        self.tableWidget_storeRcpt.setColumnCount(3)
        self.tableWidget_storeRcpt.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_storeRcpt.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_storeRcpt.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_storeRcpt.setHorizontalHeaderItem(2, item)
        self.tableWidget_storeRcpt.horizontalHeader().setDefaultSectionSize(275)
        self.label_675 = QtWidgets.QLabel(self.frame_49)
        self.label_675.setGeometry(QtCore.QRect(200, 0, 461, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_675.setFont(font)
        self.label_675.setStyleSheet("    background-color: transparent;\n"
"")
        self.label_675.setObjectName("label_675")
        self.orderReportText_2 = QtWidgets.QLabel(self.Receipts)
        self.orderReportText_2.setGeometry(QtCore.QRect(680, 10, 381, 71))
        self.orderReportText_2.setStyleSheet("color: #12245c;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"background: transparent;\n"
"font-size: 50px;")
        self.orderReportText_2.setObjectName("orderReportText_2")
        self.stackedWidget_Orders.addWidget(self.Receipts)

        self.retranslateUi(CASHIER_ORDERS)
        self.stackedWidget_Orders.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(CASHIER_ORDERS)

    def retranslateUi(self, CASHIER_ORDERS):
        _translate = QtCore.QCoreApplication.translate
        CASHIER_ORDERS.setWindowTitle(_translate("CASHIER_ORDERS", "Form"))
        self.JJelevate_text_2.setText(_translate("CASHIER_ORDERS", "J&J "))
        self.pushButton_Dashboard.setText(_translate("CASHIER_ORDERS", "  Home   "))
        self.pushButton_Order_History.setText(_translate("CASHIER_ORDERS", "Order History"))
        self.pushButton_Sales.setText(_translate("CASHIER_ORDERS", "  Sales"))
        self.pushButton_Account.setText(_translate("CASHIER_ORDERS", " Account     "))
        self.pushButton_LogOut.setText(_translate("CASHIER_ORDERS", "   Log out"))
        self.JJelevate_text_3.setText(_translate("CASHIER_ORDERS", "Elevate"))
        self.pushButton_Orders.setText(_translate("CASHIER_ORDERS", " Orders"))
        self.comboBox_filterProduct_List.setCurrentText(_translate("CASHIER_ORDERS", "    Filter Product"))
        self.comboBox_filterProduct_List.setItemText(0, _translate("CASHIER_ORDERS", "    Filter Product"))
        self.comboBox_filterProduct_List.setItemText(1, _translate("CASHIER_ORDERS", "Roof"))
        self.comboBox_filterProduct_List.setItemText(2, _translate("CASHIER_ORDERS", "Spandrel"))
        self.comboBox_filterProduct_List.setItemText(3, _translate("CASHIER_ORDERS", "Gutter"))
        self.comboBox_filterProduct_List.setItemText(4, _translate("CASHIER_ORDERS", "Others"))
        self.lineEdit__QuicksearchProduct.setPlaceholderText(_translate("CASHIER_ORDERS", "      Quick Search"))
        self.pushButton_searchProduct.setText(_translate("CASHIER_ORDERS", "Search"))
        self.orderReportText.setText(_translate("CASHIER_ORDERS", "Product List"))
        self.pushButton_Inventory_ALL_ITEMS_table.setText(_translate("CASHIER_ORDERS", "All Items"))
        self.pushButton_Inventory_ROOF_table.setText(_translate("CASHIER_ORDERS", "Roof"))
        self.pushButton_Inventory_SPANDREL_table.setText(_translate("CASHIER_ORDERS", "Spandrel"))
        self.pushButton_Inventory_GUTTER_table.setText(_translate("CASHIER_ORDERS", "Gutter"))
        self.pushButton_Inventory_OTHER_table.setText(_translate("CASHIER_ORDERS", "Other"))
        item = self.tableWidget_Product_List.horizontalHeaderItem(0)
        item.setText(_translate("CASHIER_ORDERS", "Product"))
        item = self.tableWidget_Product_List.horizontalHeaderItem(1)
        item.setText(_translate("CASHIER_ORDERS", "Category"))
        item = self.tableWidget_Product_List.horizontalHeaderItem(2)
        item.setText(_translate("CASHIER_ORDERS", "Price"))
        item = self.tableWidget_Product_List.horizontalHeaderItem(3)
        item.setText(_translate("CASHIER_ORDERS", "Available Stock"))
        item = self.tableWidget_Product_List.horizontalHeaderItem(4)
        item.setText(_translate("CASHIER_ORDERS", "Quantity"))
        self.label_644.setText(_translate("CASHIER_ORDERS", "Product      "))
        self.pushButton_Save_OTHERedit.setText(_translate("CASHIER_ORDERS", "Product Specification"))
        self.label_645.setText(_translate("CASHIER_ORDERS", "Thickness         "))
        self.OrderInput_Product.setPlaceholderText(_translate("CASHIER_ORDERS", "....."))
        self.OrderInput_Thickness.setPlaceholderText(_translate("CASHIER_ORDERS", "....."))
        self.label_646.setText(_translate("CASHIER_ORDERS", "Width"))
        self.OrderInput_Width.setPlaceholderText(_translate("CASHIER_ORDERS", "....."))
        self.OrderInput_Length.setPlaceholderText(_translate("CASHIER_ORDERS", "....."))
        self.label_647.setText(_translate("CASHIER_ORDERS", "Length"))
        self.label_648.setText(_translate("CASHIER_ORDERS", "Height"))
        self.OrderInput_Height.setPlaceholderText(_translate("CASHIER_ORDERS", "....."))
        self.label_649.setText(_translate("CASHIER_ORDERS", "Color"))
        self.OrderInput_Color.setPlaceholderText(_translate("CASHIER_ORDERS", "....."))
        self.Add_Order.setText(_translate("CASHIER_ORDERS", "Add"))
        self.Cancel_Order.setText(_translate("CASHIER_ORDERS", "Cancel "))
        self.pushButton_Save_OTHERedit_2.setText(_translate("CASHIER_ORDERS", "Order Summary"))
        item = self.tableWidget_OrderSummary.horizontalHeaderItem(0)
        item.setText(_translate("CASHIER_ORDERS", "Product"))
        item = self.tableWidget_OrderSummary.horizontalHeaderItem(1)
        item.setText(_translate("CASHIER_ORDERS", "Quantity"))
        item = self.tableWidget_OrderSummary.horizontalHeaderItem(2)
        item.setText(_translate("CASHIER_ORDERS", "Thickness"))
        item = self.tableWidget_OrderSummary.horizontalHeaderItem(3)
        item.setText(_translate("CASHIER_ORDERS", "Width"))
        item = self.tableWidget_OrderSummary.horizontalHeaderItem(4)
        item.setText(_translate("CASHIER_ORDERS", "Quantity"))
        item = self.tableWidget_OrderSummary.horizontalHeaderItem(5)
        item.setText(_translate("CASHIER_ORDERS", "Color"))
        item = self.tableWidget_OrderSummary.horizontalHeaderItem(6)
        item.setText(_translate("CASHIER_ORDERS", "Price"))
        self.label_650.setText(_translate("CASHIER_ORDERS", "Customer Name    :"))
        self.label_651.setText(_translate("CASHIER_ORDERS", "Address                    :"))
        self.OrderSummary_CusName.setPlaceholderText(_translate("CASHIER_ORDERS", "....."))
        self.OrderSummary_CusAddress.setPlaceholderText(_translate("CASHIER_ORDERS", "....."))
        self.pushButton_Save_OTHERedit_3.setText(_translate("CASHIER_ORDERS", "CUSTOMER INFORMATION"))
        self.label_653.setText(_translate("CASHIER_ORDERS", "Service         :"))
        self.label_654.setText(_translate("CASHIER_ORDERS", "Contact #   :"))
        self.OrderSummary_CusContactnum.setPlaceholderText(_translate("CASHIER_ORDERS", "....."))
        self.OrderSummary_CusService_type.setCurrentText(_translate("CASHIER_ORDERS", "Select Service Type"))
        self.OrderSummary_CusService_type.setItemText(0, _translate("CASHIER_ORDERS", "Select Service Type"))
        self.OrderSummary_CusService_type.setItemText(1, _translate("CASHIER_ORDERS", "Install"))
        self.OrderSummary_CusService_type.setItemText(2, _translate("CASHIER_ORDERS", "Repair"))
        self.OrderSummary_CusService_type.setItemText(3, _translate("CASHIER_ORDERS", "Deliver"))
        self.OrderSummary_cancelOrder.setText(_translate("CASHIER_ORDERS", "Cancel Order"))
        self.OrderSummary_submitOrder.setText(_translate("CASHIER_ORDERS", "Submit Order"))
        self.Save_Receipt.setText(_translate("CASHIER_ORDERS", "Save Receipt"))
        self.Close.setText(_translate("CASHIER_ORDERS", "Close"))
        self.label_655.setText(_translate("CASHIER_ORDERS", "Service Type"))
        self.label_652.setText(_translate("CASHIER_ORDERS", "Address"))
        self.label_657.setText(_translate("CASHIER_ORDERS", "Contact #"))
        self.label_658.setText(_translate("CASHIER_ORDERS", "Customer Name"))
        self.label_659.setText(_translate("CASHIER_ORDERS", "Processed by"))
        self.label_660.setText(_translate("CASHIER_ORDERS", "Date and Time"))
        self.label_661.setText(_translate("CASHIER_ORDERS", "Order ID"))
        self.Cancel_Order_5.setText(_translate("CASHIER_ORDERS", "Total Price"))
        self.Cancel_Order_6.setText(_translate("CASHIER_ORDERS", "Subtotal Price"))
        self.label_674.setText(_translate("CASHIER_ORDERS", "Receipt ID\n"
""))
        self.Cancel_Order_7.setText(_translate("CASHIER_ORDERS", "Discount"))
        item = self.tableWidget_storeRcpt.horizontalHeaderItem(0)
        item.setText(_translate("CASHIER_ORDERS", "Product"))
        item = self.tableWidget_storeRcpt.horizontalHeaderItem(1)
        item.setText(_translate("CASHIER_ORDERS", "Quantity  "))
        item = self.tableWidget_storeRcpt.horizontalHeaderItem(2)
        item.setText(_translate("CASHIER_ORDERS", "Price"))
        self.label_675.setText(_translate("CASHIER_ORDERS", "J & J Roofsteel and Gutter Supply"))
        self.orderReportText_2.setText(_translate("CASHIER_ORDERS", "Receipt"))
