# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/FORGOTpass.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ForgotPass(object):
    def setupUi(self, ForgotPass):
        ForgotPass.setObjectName("ForgotPass")
        ForgotPass.resize(1925, 1033)
        ForgotPass.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(ForgotPass)
        self.centralwidget.setStyleSheet("background-color: white;")
        self.centralwidget.setObjectName("centralwidget")
        self.PIC = QtWidgets.QLabel(self.centralwidget)
        self.PIC.setGeometry(QtCore.QRect(0, 0, 1921, 982))
        self.PIC.setMinimumSize(QtCore.QSize(100, 40))
        self.PIC.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.PIC.setText("")
        self.PIC.setPixmap(QtGui.QPixmap(":/JJimages/PIC_log_sign_in.png"))
        self.PIC.setScaledContents(True)
        self.PIC.setObjectName("PIC")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 130, 451, 331))
        self.label.setStyleSheet("background-color: transparent;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/JJimages/JJLOGO.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(990, 0, 931, 982))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.stackedWidget_forgotPass = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget_forgotPass.setGeometry(QtCore.QRect(0, 90, 931, 861))
        self.stackedWidget_forgotPass.setObjectName("stackedWidget_forgotPass")
        self.enter_contact = QtWidgets.QWidget()
        self.enter_contact.setObjectName("enter_contact")
        self.stackedWidget_forgotPass.addWidget(self.enter_contact)
        self.enter_verification = QtWidgets.QWidget()
        self.enter_verification.setObjectName("enter_verification")
        self.stackedWidget_forgotPass.addWidget(self.enter_verification)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame_4 = QtWidgets.QFrame(self.page)
        self.frame_4.setGeometry(QtCore.QRect(20, 30, 901, 811))
        self.frame_4.setStyleSheet("background: transparent;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(140, -10, 671, 81))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(87)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: #022162;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.setNewPass_2 = QtWidgets.QLabel(self.frame_4)
        self.setNewPass_2.setGeometry(QtCore.QRect(50, 430, 761, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(87)
        self.setNewPass_2.setFont(font)
        self.setNewPass_2.setStyleSheet("color: #022162;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;")
        self.setNewPass_2.setObjectName("setNewPass_2")
        self.setNewPass = QtWidgets.QLineEdit(self.frame_4)
        self.setNewPass.setGeometry(QtCore.QRect(40, 490, 821, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        self.setNewPass.setFont(font)
        self.setNewPass.setStyleSheet("border: 2px solid #022162; \n"
"border-radius: 25px; \n"
"padding: 5px;\n"
"font-family: \"Verdana\", sans-serif; ")
        self.setNewPass.setObjectName("setNewPass")
        self.pushButton_confirmPass_reset = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_confirmPass_reset.setGeometry(QtCore.QRect(590, 710, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(87)
        self.pushButton_confirmPass_reset.setFont(font)
        self.pushButton_confirmPass_reset.setStyleSheet("border: 2px solid #374550; \n"
"border-radius: 25px; \n"
"padding: 5px; \n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background-color: #374550; \n"
"color: white;")
        self.pushButton_confirmPass_reset.setObjectName("pushButton_confirmPass_reset")
        self.confirmPass = QtWidgets.QLabel(self.frame_4)
        self.confirmPass.setGeometry(QtCore.QRect(50, 550, 761, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(87)
        self.confirmPass.setFont(font)
        self.confirmPass.setStyleSheet("color: #022162;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;")
        self.confirmPass.setObjectName("confirmPass")
        self.confirmNewPass = QtWidgets.QLineEdit(self.frame_4)
        self.confirmNewPass.setGeometry(QtCore.QRect(40, 610, 821, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        self.confirmNewPass.setFont(font)
        self.confirmNewPass.setStyleSheet("border: 2px solid #022162; \n"
"border-radius: 25px; \n"
"padding: 5px;\n"
"font-family: \"Verdana\", sans-serif; ")
        self.confirmNewPass.setObjectName("confirmNewPass")
        self.securityAnswerField = QtWidgets.QLineEdit(self.frame_4)
        self.securityAnswerField.setGeometry(QtCore.QRect(40, 360, 821, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        self.securityAnswerField.setFont(font)
        self.securityAnswerField.setStyleSheet("border: 2px solid #022162; \n"
"border-radius: 25px; \n"
"padding: 5px;\n"
"font-family: \"Verdana\", sans-serif; ")
        self.securityAnswerField.setObjectName("securityAnswerField")
        self.label_secQuestionText = QtWidgets.QLabel(self.frame_4)
        self.label_secQuestionText.setGeometry(QtCore.QRect(40, 250, 761, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(87)
        self.label_secQuestionText.setFont(font)
        self.label_secQuestionText.setStyleSheet("color: #022162;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;")
        self.label_secQuestionText.setObjectName("label_secQuestionText")
        self.checkUser = QtWidgets.QLineEdit(self.frame_4)
        self.checkUser.setGeometry(QtCore.QRect(40, 180, 511, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        self.checkUser.setFont(font)
        self.checkUser.setStyleSheet("border: 2px solid #022162; \n"
"border-radius: 25px; \n"
"padding: 5px;\n"
"font-family: \"Verdana\", sans-serif; ")
        self.checkUser.setObjectName("checkUser")
        self.checkUser_2 = QtWidgets.QLabel(self.frame_4)
        self.checkUser_2.setGeometry(QtCore.QRect(40, 120, 761, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(87)
        self.checkUser_2.setFont(font)
        self.checkUser_2.setStyleSheet("color: #022162;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;")
        self.checkUser_2.setObjectName("checkUser_2")
        self.pushButton_checkUsername = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_checkUsername.setGeometry(QtCore.QRect(600, 180, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(87)
        self.pushButton_checkUsername.setFont(font)
        self.pushButton_checkUsername.setStyleSheet("border: 2px solid #374550; \n"
"border-radius: 25px; \n"
"padding: 5px; \n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background-color: #374550; \n"
"color: white;")
        self.pushButton_checkUsername.setObjectName("pushButton_checkUsername")
        self.pushButton_cancelPass = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_cancelPass.setGeometry(QtCore.QRect(320, 710, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(87)
        self.pushButton_cancelPass.setFont(font)
        self.pushButton_cancelPass.setStyleSheet("border: 2px solid #374550; \n"
"border-radius: 25px; \n"
"padding: 5px; \n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background-color: #374550; \n"
"color: white;")
        self.pushButton_cancelPass.setObjectName("pushButton_cancelPass")
        self.toggleNewPass = QtWidgets.QPushButton(self.frame_4)
        self.toggleNewPass.setGeometry(QtCore.QRect(780, 505, 61, 31))
        self.toggleNewPass.setStyleSheet("QPushButton#togglePasswordButton {\n"
"    border: none;          /* Removes the border */\n"
"    background-color: transparent; /* Transparent background */\n"
"    padding: 2px;          /* Optional: Adds a bit of spacing */\n"
"}\n"
"\n"
"")
        self.toggleNewPass.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("views\\../../../../../Downloads/EYE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toggleNewPass.setIcon(icon)
        self.toggleNewPass.setIconSize(QtCore.QSize(45, 45))
        self.toggleNewPass.setObjectName("toggleNewPass")
        self.toggleConfirmPass = QtWidgets.QPushButton(self.frame_4)
        self.toggleConfirmPass.setGeometry(QtCore.QRect(780, 630, 61, 21))
        self.toggleConfirmPass.setStyleSheet("QPushButton#togglePasswordButton {\n"
"    border: none;          /* Removes the border */\n"
"    background-color: transparent; /* Transparent background */\n"
"    padding: 2px;          /* Optional: Adds a bit of spacing */\n"
"}\n"
"\n"
"")
        self.toggleConfirmPass.setText("")
        self.toggleConfirmPass.setIcon(icon)
        self.toggleConfirmPass.setIconSize(QtCore.QSize(45, 45))
        self.toggleConfirmPass.setObjectName("toggleConfirmPass")
        self.label_secQuestion = QtWidgets.QLabel(self.frame_4)
        self.label_secQuestion.setGeometry(QtCore.QRect(40, 300, 761, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(87)
        self.label_secQuestion.setFont(font)
        self.label_secQuestion.setStyleSheet("color: #022162;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;")
        self.label_secQuestion.setText("")
        self.label_secQuestion.setObjectName("label_secQuestion")
        self.stackedWidget_forgotPass.addWidget(self.page)
        self.pushButton_xtolanding_forgotpass_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_xtolanding_forgotpass_2.setGeometry(QtCore.QRect(680, 30, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.pushButton_xtolanding_forgotpass_2.setFont(font)
        self.pushButton_xtolanding_forgotpass_2.setStyleSheet("border-radius: 13px; \n"
"padding: 1px; \n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"font-size: 18px;\n"
"background-color: #374550; \n"
"color: white;")
        self.pushButton_xtolanding_forgotpass_2.setObjectName("pushButton_xtolanding_forgotpass_2")
        self.jframe = QtWidgets.QFrame(self.centralwidget)
        self.jframe.setGeometry(QtCore.QRect(-10, 460, 951, 431))
        self.jframe.setStyleSheet("background: transparent;")
        self.jframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.jframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.jframe.setObjectName("jframe")
        self.label_18 = QtWidgets.QLabel(self.jframe)
        self.label_18.setGeometry(QtCore.QRect(120, 20, 771, 111))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(87)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: #ffffff;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;\n"
"")
        self.label_18.setObjectName("label_18")
        self.label_6 = QtWidgets.QLabel(self.jframe)
        self.label_6.setGeometry(QtCore.QRect(340, 110, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(87)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: #ffffff;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_11 = QtWidgets.QLabel(self.jframe)
        self.label_11.setGeometry(QtCore.QRect(170, 250, 631, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(87)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: #fff2bd; \n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent; \n"
"")
        self.label_11.setObjectName("label_11")
        ForgotPass.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ForgotPass)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1925, 26))
        self.menubar.setObjectName("menubar")
        ForgotPass.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ForgotPass)
        self.statusbar.setObjectName("statusbar")
        ForgotPass.setStatusBar(self.statusbar)

        self.retranslateUi(ForgotPass)
        self.stackedWidget_forgotPass.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(ForgotPass)

    def retranslateUi(self, ForgotPass):
        _translate = QtCore.QCoreApplication.translate
        ForgotPass.setWindowTitle(_translate("ForgotPass", "Inventory and Sales Management System"))
        self.label_9.setText(_translate("ForgotPass", "Reset Password"))
        self.setNewPass_2.setText(_translate("ForgotPass", "Set New Password"))
        self.setNewPass.setPlaceholderText(_translate("ForgotPass", "  Enter your new password"))
        self.pushButton_confirmPass_reset.setText(_translate("ForgotPass", "Confirm"))
        self.confirmPass.setText(_translate("ForgotPass", "Confirm New Password"))
        self.confirmNewPass.setPlaceholderText(_translate("ForgotPass", "  Enter your confirm password"))
        self.securityAnswerField.setPlaceholderText(_translate("ForgotPass", "  Enter your answer"))
        self.label_secQuestionText.setText(_translate("ForgotPass", "Security Question"))
        self.checkUser.setPlaceholderText(_translate("ForgotPass", "  Enter your username"))
        self.checkUser_2.setText(_translate("ForgotPass", "Username"))
        self.pushButton_checkUsername.setText(_translate("ForgotPass", "Check"))
        self.pushButton_cancelPass.setText(_translate("ForgotPass", "Cancel"))
        self.pushButton_xtolanding_forgotpass_2.setText(_translate("ForgotPass", "← Back to Login"))
        self.label_18.setText(_translate("ForgotPass", "J & J Roofsteel and Gutter Supply"))
        self.label_6.setText(_translate("ForgotPass", "Moalboal Branch"))
        self.label_11.setText(_translate("ForgotPass", "Supply       |         Install       |         Repair    "))
import resources.jj_owner_resources_rc
