# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/LOGIN.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LOGIN(object):
    def setupUi(self, LOGIN):
        LOGIN.setObjectName("LOGIN")
        LOGIN.resize(1925, 1033)
        LOGIN.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(LOGIN)
        self.centralwidget.setStyleSheet("background-color: white;")
        self.centralwidget.setObjectName("centralwidget")
        self.PIC = QtWidgets.QLabel(self.centralwidget)
        self.PIC.setGeometry(QtCore.QRect(0, 0, 1921, 982))
        self.PIC.setMinimumSize(QtCore.QSize(100, 40))
        self.PIC.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.PIC.setText("")
        self.PIC.setPixmap(QtGui.QPixmap(":/JJimages/PIC_log_sign_in.png"))
        self.PIC.setScaledContents(True)
        self.PIC.setObjectName("PIC")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 130, 451, 331))
        self.label.setStyleSheet("background-color: transparent;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/JJimages/JJLOGO.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(990, 0, 931, 982))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.checkBox_rememberme = QtWidgets.QCheckBox(self.frame)
        self.checkBox_rememberme.setGeometry(QtCore.QRect(60, 610, 201, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        self.checkBox_rememberme.setFont(font)
        self.checkBox_rememberme.setStyleSheet("color: #022162;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;")
        self.checkBox_rememberme.setObjectName("checkBox_rememberme")
        self.pushButton_xtolanding = QtWidgets.QPushButton(self.frame)
        self.pushButton_xtolanding.setGeometry(QtCore.QRect(670, 50, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.pushButton_xtolanding.setFont(font)
        self.pushButton_xtolanding.setStyleSheet("border-radius: 13px; \n"
"padding: 1px; \n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"font-size: 18px;\n"
"background-color: #374550; \n"
"color: white;")
        self.pushButton_xtolanding.setObjectName("pushButton_xtolanding")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(340, 130, 261, 131))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(47)
        font.setBold(True)
        font.setWeight(87)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #022162;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;")
        self.label_2.setObjectName("label_2")
        self.username = QtWidgets.QLabel(self.frame)
        self.username.setGeometry(QtCore.QRect(60, 310, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(87)
        self.username.setFont(font)
        self.username.setStyleSheet("color: #022162;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLabel(self.frame)
        self.password.setGeometry(QtCore.QRect(60, 460, 181, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(87)
        self.password.setFont(font)
        self.password.setStyleSheet("color: #022162;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;")
        self.password.setObjectName("password")
        self.login_usrname = QtWidgets.QLineEdit(self.frame)
        self.login_usrname.setGeometry(QtCore.QRect(50, 370, 841, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        self.login_usrname.setFont(font)
        self.login_usrname.setStyleSheet("border: 2px solid #022162; \n"
"border-radius: 25px; \n"
"padding: 5px;\n"
"font-family: \"Verdana\", sans-serif; ")
        self.login_usrname.setObjectName("login_usrname")
        self.login_password = QtWidgets.QLineEdit(self.frame)
        self.login_password.setGeometry(QtCore.QRect(50, 530, 831, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        self.login_password.setFont(font)
        self.login_password.setStyleSheet("border: 2px solid #022162; \n"
"border-radius: 25px; \n"
"padding: 5px;\n"
"font-family: \"Verdana\", sans-serif; ")
        self.login_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.login_password.setObjectName("login_password")
        self.pushButton_LOGIN = QtWidgets.QPushButton(self.frame)
        self.pushButton_LOGIN.setGeometry(QtCore.QRect(640, 700, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(87)
        self.pushButton_LOGIN.setFont(font)
        self.pushButton_LOGIN.setStyleSheet("border: 2px solid #374550; \n"
"border-radius: 25px; \n"
"padding: 5px; \n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background-color: #374550; \n"
"color: white;")
        self.pushButton_LOGIN.setObjectName("pushButton_LOGIN")
        self.forgotPassLabel = QtWidgets.QLabel(self.frame)
        self.forgotPassLabel.setGeometry(QtCore.QRect(60, 680, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.forgotPassLabel.setFont(font)
        self.forgotPassLabel.setStyleSheet("color: #022162;\n"
"font-family: \"Verdana\", sans-serif; \n"
"font-size: 14px;\n"
"background: transparent;")
        self.forgotPassLabel.setObjectName("forgotPassLabel")
        self.pushButton_forgotPass_login_page = QtWidgets.QPushButton(self.frame)
        self.pushButton_forgotPass_login_page.setGeometry(QtCore.QRect(120, 720, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(87)
        self.pushButton_forgotPass_login_page.setFont(font)
        self.pushButton_forgotPass_login_page.setStyleSheet("border-radius: 25px; \n"
"padding: 5px; \n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background-color: transparent; \n"
"color: #022162;")
        self.pushButton_forgotPass_login_page.setObjectName("pushButton_forgotPass_login_page")
        self.togglePasswordButton = QtWidgets.QPushButton(self.frame)
        self.togglePasswordButton.setGeometry(QtCore.QRect(810, 540, 51, 41))
        self.togglePasswordButton.setStyleSheet("QPushButton#togglePasswordButton {\n"
"    border: none;          /* Removes the border */\n"
"    background-color: transparent; /* Transparent background */\n"
"    padding: 2px;          /* Optional: Adds a bit of spacing */\n"
"}\n"
"\n"
"")
        self.togglePasswordButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("views\\../../../Downloads/EYE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.togglePasswordButton.setIcon(icon)
        self.togglePasswordButton.setIconSize(QtCore.QSize(45, 45))
        self.togglePasswordButton.setObjectName("togglePasswordButton")
        self.pushButton_clearLogins = QtWidgets.QPushButton(self.frame)
        self.pushButton_clearLogins.setGeometry(QtCore.QRect(740, 600, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_clearLogins.setFont(font)
        self.pushButton_clearLogins.setStyleSheet("border-radius: 25px; \n"
"padding: 5px; \n"
"font-size: 20px;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background-color: #c25b55; \n"
"color: white;")
        self.pushButton_clearLogins.setObjectName("pushButton_clearLogins")
        self.jframe = QtWidgets.QFrame(self.centralwidget)
        self.jframe.setGeometry(QtCore.QRect(-10, 460, 951, 431))
        self.jframe.setStyleSheet("background: transparent;")
        self.jframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.jframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.jframe.setObjectName("jframe")
        self.label_18 = QtWidgets.QLabel(self.jframe)
        self.label_18.setGeometry(QtCore.QRect(120, 20, 771, 111))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(87)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: #ffffff;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;\n"
"")
        self.label_18.setObjectName("label_18")
        self.label_6 = QtWidgets.QLabel(self.jframe)
        self.label_6.setGeometry(QtCore.QRect(340, 110, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(87)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: #ffffff;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_11 = QtWidgets.QLabel(self.jframe)
        self.label_11.setGeometry(QtCore.QRect(170, 250, 631, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(87)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: #fff2bd; \n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent; \n"
"")
        self.label_11.setObjectName("label_11")
        LOGIN.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LOGIN)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1925, 26))
        self.menubar.setObjectName("menubar")
        LOGIN.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LOGIN)
        self.statusbar.setObjectName("statusbar")
        LOGIN.setStatusBar(self.statusbar)

        self.retranslateUi(LOGIN)
        QtCore.QMetaObject.connectSlotsByName(LOGIN)

    def retranslateUi(self, LOGIN):
        _translate = QtCore.QCoreApplication.translate
        LOGIN.setWindowTitle(_translate("LOGIN", "Inventory and Sales Management System"))
        self.checkBox_rememberme.setText(_translate("LOGIN", "Remember me"))
        self.pushButton_xtolanding.setText(_translate("LOGIN", "← Back to Landing"))
        self.label_2.setText(_translate("LOGIN", "Login"))
        self.username.setText(_translate("LOGIN", "Username"))
        self.password.setText(_translate("LOGIN", "Password"))
        self.login_usrname.setPlaceholderText(_translate("LOGIN", "  Enter your username"))
        self.login_password.setPlaceholderText(_translate("LOGIN", "  Enter your password"))
        self.pushButton_LOGIN.setText(_translate("LOGIN", "Login"))
        self.forgotPassLabel.setText(_translate("LOGIN", "Forgot password? Only available for Shop Owners"))
        self.pushButton_forgotPass_login_page.setText(_translate("LOGIN", "Reset Password"))
        self.pushButton_clearLogins.setText(_translate("LOGIN", "Clear "))
        self.label_18.setText(_translate("LOGIN", "J & J Roofsteel and Gutter Supply"))
        self.label_6.setText(_translate("LOGIN", "Moalboal Branch"))
        self.label_11.setText(_translate("LOGIN", "Supply       |         Install       |         Repair    "))

import resources.resources_rc
