# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/UI_ODashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OWNER_DASHBOARD(object):
    def setupUi(self, OWNER_DASHBOARD):
        OWNER_DASHBOARD.setObjectName("OWNER_DASHBOARD")
        OWNER_DASHBOARD.resize(1921, 1005)
        OWNER_DASHBOARD.setStyleSheet("background: white;")
        self.frame_45 = QtWidgets.QFrame(OWNER_DASHBOARD)
        self.frame_45.setGeometry(QtCore.QRect(300, 0, 1621, 211))
        self.frame_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.timeLabel = QtWidgets.QLabel(self.frame_45)
        self.timeLabel.setGeometry(QtCore.QRect(840, 20, 731, 171))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.timeLabel.setFont(font)
        self.timeLabel.setStyleSheet("\n"
"    background-color: #f6f3ee;\n"
"    border-radius: 16;\n"
"    padding: 10px;\n"
"color: #051a54;\n"
"")
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.dateLabel = QtWidgets.QLabel(self.frame_45)
        self.dateLabel.setGeometry(QtCore.QRect(40, 20, 771, 171))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setBold(True)
        font.setWeight(75)
        self.dateLabel.setFont(font)
        self.dateLabel.setStyleSheet("\n"
"    background-color: #f6f3ee;\n"
"    border-radius: 16;\n"
"    padding: 10px;\n"
"\n"
"")
        self.dateLabel.setTextFormat(QtCore.Qt.RichText)
        self.dateLabel.setObjectName("dateLabel")
        self.frame_46 = QtWidgets.QFrame(OWNER_DASHBOARD)
        self.frame_46.setGeometry(QtCore.QRect(340, 210, 1531, 761))
        self.frame_46.setStyleSheet("\n"
"    background-color: #f6f3ee;\n"
"    border-radius: 16;\n"
"    padding: 10px;\n"
"\n"
"")
        self.frame_46.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.Todays_Sales_box = QtWidgets.QFrame(self.frame_46)
        self.Todays_Sales_box.setGeometry(QtCore.QRect(770, 30, 361, 161))
        self.Todays_Sales_box.setStyleSheet("#salesbox\n"
"{\n"
"border: 1px solid black;\n"
"border-radius: 10px;\n"
"    background-color: white;\n"
"    border: 2px solid black;\n"
"    padding: 10px;\n"
"}")
        self.Todays_Sales_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Todays_Sales_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Todays_Sales_box.setObjectName("Todays_Sales_box")
        self.salesbox = QtWidgets.QLabel(self.Todays_Sales_box)
        self.salesbox.setGeometry(QtCore.QRect(20, 20, 321, 131))
        self.salesbox.setStyleSheet("\n"
"    background-color: #374550;\n"
"    border-radius: 25;\n"
"    padding: 10px;\n"
"\n"
"")
        self.salesbox.setText("")
        self.salesbox.setObjectName("salesbox")
        self.value_Tod_sales = QtWidgets.QLabel(self.Todays_Sales_box)
        self.value_Tod_sales.setGeometry(QtCore.QRect(50, 50, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.value_Tod_sales.setFont(font)
        self.value_Tod_sales.setStyleSheet("color:#ebe0cc;\n"
"background: transparent;\n"
"")
        self.value_Tod_sales.setText("")
        self.value_Tod_sales.setAlignment(QtCore.Qt.AlignCenter)
        self.value_Tod_sales.setObjectName("value_Tod_sales")
        self.label_4 = QtWidgets.QLabel(self.Todays_Sales_box)
        self.label_4.setGeometry(QtCore.QRect(80, 100, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #ffffff;\n"
"background: transparent;")
        self.label_4.setObjectName("label_4")
        self.Todays_total_orders_box = QtWidgets.QFrame(self.frame_46)
        self.Todays_total_orders_box.setGeometry(QtCore.QRect(1140, 30, 361, 161))
        self.Todays_total_orders_box.setStyleSheet("#ordersbox\n"
"{\n"
"border: 1px solid black;\n"
"border-radius: 10px;\n"
"}")
        self.Todays_total_orders_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Todays_total_orders_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Todays_total_orders_box.setObjectName("Todays_total_orders_box")
        self.ordersbox = QtWidgets.QLabel(self.Todays_total_orders_box)
        self.ordersbox.setGeometry(QtCore.QRect(10, 20, 341, 131))
        self.ordersbox.setStyleSheet("\n"
"    background-color: #c25b55;\n"
"    border-radius: 25;\n"
"    padding: 10px;\n"
"\n"
"")
        self.ordersbox.setText("")
        self.ordersbox.setObjectName("ordersbox")
        self.value_Tod_orders = QtWidgets.QLabel(self.Todays_total_orders_box)
        self.value_Tod_orders.setGeometry(QtCore.QRect(100, 40, 161, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.value_Tod_orders.setFont(font)
        self.value_Tod_orders.setStyleSheet("color: #ebe0cc;\n"
"background: transparent;")
        self.value_Tod_orders.setText("")
        self.value_Tod_orders.setAlignment(QtCore.Qt.AlignCenter)
        self.value_Tod_orders.setObjectName("value_Tod_orders")
        self.label_8 = QtWidgets.QLabel(self.Todays_total_orders_box)
        self.label_8.setGeometry(QtCore.QRect(40, 90, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: #ffffff;\n"
"background: transparent;")
        self.label_8.setObjectName("label_8")
        self.dashboard_bestsellers_box = QtWidgets.QFrame(self.frame_46)
        self.dashboard_bestsellers_box.setGeometry(QtCore.QRect(30, 210, 711, 521))
        self.dashboard_bestsellers_box.setStyleSheet("#chartd\n"
"{\n"
"border: 1px solid black;\n"
"border-radius: 10px;\n"
"}")
        self.dashboard_bestsellers_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dashboard_bestsellers_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dashboard_bestsellers_box.setObjectName("dashboard_bestsellers_box")
        self.frameBestSellersChart = QtWidgets.QFrame(self.dashboard_bestsellers_box)
        self.frameBestSellersChart.setGeometry(QtCore.QRect(20, 80, 661, 391))
        self.frameBestSellersChart.setStyleSheet("background-color: transparent;\n"
"")
        self.frameBestSellersChart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBestSellersChart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBestSellersChart.setObjectName("frameBestSellersChart")
        self.bestsellersbox = QtWidgets.QLabel(self.dashboard_bestsellers_box)
        self.bestsellersbox.setGeometry(QtCore.QRect(0, 0, 701, 521))
        self.bestsellersbox.setStyleSheet("\n"
"    background-color: transparent;\n"
"    border-radius: 25;\n"
"    padding: 10px;\n"
"\n"
"    border: 2px solid #b2423c;\n"
"\n"
"")
        self.bestsellersbox.setText("")
        self.bestsellersbox.setObjectName("bestsellersbox")
        self.label_10 = QtWidgets.QLabel(self.dashboard_bestsellers_box)
        self.label_10.setGeometry(QtCore.QRect(180, 0, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: #201f1d;\n"
"background: transparent;")
        self.label_10.setObjectName("label_10")
        self.btnViewSalesReport = QtWidgets.QPushButton(self.dashboard_bestsellers_box)
        self.btnViewSalesReport.setGeometry(QtCore.QRect(220, 470, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setUnderline(True)
        self.btnViewSalesReport.setFont(font)
        self.btnViewSalesReport.setStyleSheet("QPushButton{color: #004aad;\n"
"text-decoration: underline;\n"
"border: none;\n"
"font-size: 24px;\n"
"background: transparent;}\n"
"QPushButton:hover {\n"
"color:#8d2721;\n"
"}\n"
"")
        self.btnViewSalesReport.setObjectName("btnViewSalesReport")
        self.bestsellersbox.raise_()
        self.frameBestSellersChart.raise_()
        self.label_10.raise_()
        self.btnViewSalesReport.raise_()
        self.low_inventory = QtWidgets.QFrame(self.frame_46)
        self.low_inventory.setGeometry(QtCore.QRect(760, 210, 741, 521))
        self.low_inventory.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.low_inventory.setFrameShadow(QtWidgets.QFrame.Raised)
        self.low_inventory.setObjectName("low_inventory")
        self.lowstockbox = QtWidgets.QLabel(self.low_inventory)
        self.lowstockbox.setGeometry(QtCore.QRect(20, 0, 721, 521))
        self.lowstockbox.setStyleSheet("\n"
"    background-color: transparent;\n"
"    border-radius: 25;\n"
"    padding: 10px;\n"
"\n"
"    border: 2px solid #b2423c;\n"
"\n"
"")
        self.lowstockbox.setText("")
        self.lowstockbox.setObjectName("lowstockbox")
        self.dotline_4 = QtWidgets.QLabel(self.low_inventory)
        self.dotline_4.setGeometry(QtCore.QRect(0, 430, 741, 121))
        self.dotline_4.setStyleSheet("background: transparent;")
        self.dotline_4.setText("")
        self.dotline_4.setPixmap(QtGui.QPixmap("views\\../resources/images/dottedline.png"))
        self.dotline_4.setScaledContents(True)
        self.dotline_4.setObjectName("dotline_4")
        self.dotline_3 = QtWidgets.QLabel(self.low_inventory)
        self.dotline_3.setGeometry(QtCore.QRect(0, 350, 741, 171))
        self.dotline_3.setStyleSheet("background: transparent;")
        self.dotline_3.setText("")
        self.dotline_3.setPixmap(QtGui.QPixmap("views\\../resources/images/dottedline.png"))
        self.dotline_3.setScaledContents(True)
        self.dotline_3.setObjectName("dotline_3")
        self.dotline_2 = QtWidgets.QLabel(self.low_inventory)
        self.dotline_2.setGeometry(QtCore.QRect(0, 280, 741, 191))
        self.dotline_2.setStyleSheet("background: transparent;")
        self.dotline_2.setText("")
        self.dotline_2.setPixmap(QtGui.QPixmap("views\\../resources/images/dottedline.png"))
        self.dotline_2.setScaledContents(True)
        self.dotline_2.setObjectName("dotline_2")
        self.dotline_1 = QtWidgets.QLabel(self.low_inventory)
        self.dotline_1.setGeometry(QtCore.QRect(0, 200, 751, 251))
        self.dotline_1.setStyleSheet("background: transparent;")
        self.dotline_1.setText("")
        self.dotline_1.setPixmap(QtGui.QPixmap("views\\../resources/images/dottedline.png"))
        self.dotline_1.setScaledContents(True)
        self.dotline_1.setObjectName("dotline_1")
        self.label_11 = QtWidgets.QLabel(self.low_inventory)
        self.label_11.setGeometry(QtCore.QRect(250, 0, 281, 81))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: #201f1d;\n"
"background: transparent;")
        self.label_11.setObjectName("label_11")
        self.btnViewMore_Inventory = QtWidgets.QPushButton(self.low_inventory)
        self.btnViewMore_Inventory.setGeometry(QtCore.QRect(230, 470, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setUnderline(True)
        self.btnViewMore_Inventory.setFont(font)
        self.btnViewMore_Inventory.setStyleSheet("QPushButton{color: #004aad;\n"
"text-decoration: underline;\n"
"font-size: 24px;\n"
"border: none;\n"
"background: transparent;}\n"
"QPushButton:hover {\n"
"color:#8d2721;\n"
"}\n"
"")
        self.btnViewMore_Inventory.setObjectName("btnViewMore_Inventory")
        self.dashb_lowinstock_value = QtWidgets.QLabel(self.low_inventory)
        self.dashb_lowinstock_value.setGeometry(QtCore.QRect(560, 80, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.dashb_lowinstock_value.setFont(font)
        self.dashb_lowinstock_value.setStyleSheet("color: #d75413;\n"
"background: transparent;")
        self.dashb_lowinstock_value.setText("")
        self.dashb_lowinstock_value.setObjectName("dashb_lowinstock_value")
        self.label_12 = QtWidgets.QLabel(self.low_inventory)
        self.label_12.setGeometry(QtCore.QRect(50, 80, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(15)
        font.setItalic(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.low_inventory)
        self.label_13.setGeometry(QtCore.QRect(60, 130, 641, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        font.setItalic(True)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: white;\n"
"border-radius: 15px; \n"
"padding: 3px; \n"
"background-color: #c25b55;\n"
"")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.lowstock_product_label_1 = QtWidgets.QLabel(self.low_inventory)
        self.lowstock_product_label_1.setGeometry(QtCore.QRect(60, 200, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        self.lowstock_product_label_1.setFont(font)
        self.lowstock_product_label_1.setStyleSheet("color: #000000;\n"
"background: transparent;\n"
"")
        self.lowstock_product_label_1.setText("")
        self.lowstock_product_label_1.setObjectName("lowstock_product_label_1")
        self.lowstock_qty_label_1 = QtWidgets.QLabel(self.low_inventory)
        self.lowstock_qty_label_1.setGeometry(QtCore.QRect(470, 200, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        self.lowstock_qty_label_1.setFont(font)
        self.lowstock_qty_label_1.setStyleSheet("color: #b2423c;\n"
"background:transparent;\n"
"")
        self.lowstock_qty_label_1.setText("")
        self.lowstock_qty_label_1.setObjectName("lowstock_qty_label_1")
        self.lowstock_product_label_2 = QtWidgets.QLabel(self.low_inventory)
        self.lowstock_product_label_2.setGeometry(QtCore.QRect(60, 270, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        self.lowstock_product_label_2.setFont(font)
        self.lowstock_product_label_2.setStyleSheet("color: #000000;\n"
"background: transparent;\n"
"")
        self.lowstock_product_label_2.setText("")
        self.lowstock_product_label_2.setObjectName("lowstock_product_label_2")
        self.lowstock_qty_label_2 = QtWidgets.QLabel(self.low_inventory)
        self.lowstock_qty_label_2.setGeometry(QtCore.QRect(470, 270, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        self.lowstock_qty_label_2.setFont(font)
        self.lowstock_qty_label_2.setStyleSheet("color: #b2423c;\n"
"background:transparent;\n"
"")
        self.lowstock_qty_label_2.setText("")
        self.lowstock_qty_label_2.setObjectName("lowstock_qty_label_2")
        self.lowstock_product_label_3 = QtWidgets.QLabel(self.low_inventory)
        self.lowstock_product_label_3.setGeometry(QtCore.QRect(60, 340, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        self.lowstock_product_label_3.setFont(font)
        self.lowstock_product_label_3.setStyleSheet("color: #000000;\n"
"background: transparent;\n"
"")
        self.lowstock_product_label_3.setText("")
        self.lowstock_product_label_3.setObjectName("lowstock_product_label_3")
        self.lowstock_product_label_4 = QtWidgets.QLabel(self.low_inventory)
        self.lowstock_product_label_4.setGeometry(QtCore.QRect(60, 410, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        self.lowstock_product_label_4.setFont(font)
        self.lowstock_product_label_4.setStyleSheet("color: #000000;\n"
"background: transparent;\n"
"")
        self.lowstock_product_label_4.setText("")
        self.lowstock_product_label_4.setObjectName("lowstock_product_label_4")
        self.lowstock_qty_label_3 = QtWidgets.QLabel(self.low_inventory)
        self.lowstock_qty_label_3.setGeometry(QtCore.QRect(470, 340, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        self.lowstock_qty_label_3.setFont(font)
        self.lowstock_qty_label_3.setStyleSheet("color: #b2423c;\n"
"background:transparent;\n"
"")
        self.lowstock_qty_label_3.setText("")
        self.lowstock_qty_label_3.setObjectName("lowstock_qty_label_3")
        self.lowstock_qty_label_4 = QtWidgets.QLabel(self.low_inventory)
        self.lowstock_qty_label_4.setGeometry(QtCore.QRect(470, 410, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        self.lowstock_qty_label_4.setFont(font)
        self.lowstock_qty_label_4.setStyleSheet("color: #b2423c;\n"
"background:transparent;\n"
"")
        self.lowstock_qty_label_4.setText("")
        self.lowstock_qty_label_4.setObjectName("lowstock_qty_label_4")
        self.lowstockbox.raise_()
        self.label_11.raise_()
        self.dashb_lowinstock_value.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.dotline_4.raise_()
        self.dotline_3.raise_()
        self.dotline_2.raise_()
        self.dotline_1.raise_()
        self.lowstock_product_label_1.raise_()
        self.lowstock_qty_label_1.raise_()
        self.btnViewMore_Inventory.raise_()
        self.lowstock_product_label_2.raise_()
        self.lowstock_qty_label_2.raise_()
        self.lowstock_product_label_3.raise_()
        self.lowstock_product_label_4.raise_()
        self.lowstock_qty_label_3.raise_()
        self.lowstock_qty_label_4.raise_()
        self.AdminDashboard = QtWidgets.QLabel(self.frame_46)
        self.AdminDashboard.setGeometry(QtCore.QRect(20, 60, 691, 81))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(41)
        font.setBold(True)
        font.setWeight(75)
        self.AdminDashboard.setFont(font)
        self.AdminDashboard.setStyleSheet("color: #022162;\n"
"background: transparent;")
        self.AdminDashboard.setObjectName("AdminDashboard")
        self.LeftMenuBar = QtWidgets.QFrame(OWNER_DASHBOARD)
        self.LeftMenuBar.setGeometry(QtCore.QRect(0, 0, 301, 1011))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LeftMenuBar.setFont(font)
        self.LeftMenuBar.setStyleSheet("background-color: rgba(235, 224, 204, 0.47); /* #ebe0cc with 47% opacity */")
        self.LeftMenuBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LeftMenuBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LeftMenuBar.setObjectName("LeftMenuBar")
        self.JJelevate_text_2 = QtWidgets.QLabel(self.LeftMenuBar)
        self.JJelevate_text_2.setGeometry(QtCore.QRect(60, 220, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.JJelevate_text_2.setFont(font)
        self.JJelevate_text_2.setStyleSheet("color: #12245c;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"background: transparent;\n"
"font-size: 30px;")
        self.JJelevate_text_2.setScaledContents(True)
        self.JJelevate_text_2.setObjectName("JJelevate_text_2")
        self.Logo = QtWidgets.QLabel(self.LeftMenuBar)
        self.Logo.setGeometry(QtCore.QRect(30, 50, 241, 171))
        self.Logo.setStyleSheet("background: transparent;")
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("views\\../resources/images/JJLOGO.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setAlignment(QtCore.Qt.AlignCenter)
        self.Logo.setObjectName("Logo")
        self.pushButton_Dashboard = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Dashboard.setGeometry(QtCore.QRect(30, 310, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_Dashboard.setFont(font)
        self.pushButton_Dashboard.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("views\\../resources/images/dashboard_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Dashboard.setIcon(icon)
        self.pushButton_Dashboard.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Dashboard.setObjectName("pushButton_Dashboard")
        self.pushButton_Inventory = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Inventory.setGeometry(QtCore.QRect(30, 390, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Inventory.setFont(font)
        self.pushButton_Inventory.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("views\\../resources/images/inventory_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Inventory.setIcon(icon1)
        self.pushButton_Inventory.setIconSize(QtCore.QSize(50, 45))
        self.pushButton_Inventory.setObjectName("pushButton_Inventory")
        self.pushButton_Orders = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Orders.setGeometry(QtCore.QRect(30, 470, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Orders.setFont(font)
        self.pushButton_Orders.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("views\\../resources/images/orders_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Orders.setIcon(icon2)
        self.pushButton_Orders.setIconSize(QtCore.QSize(46, 42))
        self.pushButton_Orders.setObjectName("pushButton_Orders")
        self.pushButton_Sales = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Sales.setGeometry(QtCore.QRect(30, 550, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Sales.setFont(font)
        self.pushButton_Sales.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("views\\../resources/images/sales_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Sales.setIcon(icon3)
        self.pushButton_Sales.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_Sales.setObjectName("pushButton_Sales")
        self.pushButton_Account = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Account.setGeometry(QtCore.QRect(30, 710, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Account.setFont(font)
        self.pushButton_Account.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("views\\../resources/images/account_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Account.setIcon(icon4)
        self.pushButton_Account.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_Account.setObjectName("pushButton_Account")
        self.pushButton_LogOut = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_LogOut.setGeometry(QtCore.QRect(30, 890, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(87)
        self.pushButton_LogOut.setFont(font)
        self.pushButton_LogOut.setStyleSheet("QPushButton {\n"
"    background-color:#022162;\n"
"color:white;\n"
"font-weight: 700;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"font-size: 14;\n"
"text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"        background-color: rgba(2, 33, 98, 0.8);\n"
"        color: white;\n"
"    font-weight: 700;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("views\\../resources/images/WHITElogout_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_LogOut.setIcon(icon5)
        self.pushButton_LogOut.setIconSize(QtCore.QSize(38, 38))
        self.pushButton_LogOut.setObjectName("pushButton_LogOut")
        self.pushButton_Stock_History = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Stock_History.setGeometry(QtCore.QRect(30, 630, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Stock_History.setFont(font)
        self.pushButton_Stock_History.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        self.pushButton_Stock_History.setIcon(icon1)
        self.pushButton_Stock_History.setIconSize(QtCore.QSize(50, 45))
        self.pushButton_Stock_History.setObjectName("pushButton_Stock_History")
        self.JJelevate_text_3 = QtWidgets.QLabel(self.LeftMenuBar)
        self.JJelevate_text_3.setGeometry(QtCore.QRect(130, 220, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.JJelevate_text_3.setFont(font)
        self.JJelevate_text_3.setStyleSheet("color: #d75413;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"background: transparent;\n"
"font-size: 29px;\n"
"")
        self.JJelevate_text_3.setScaledContents(True)
        self.JJelevate_text_3.setObjectName("JJelevate_text_3")

        self.retranslateUi(OWNER_DASHBOARD)
        QtCore.QMetaObject.connectSlotsByName(OWNER_DASHBOARD)

    def retranslateUi(self, OWNER_DASHBOARD):
        _translate = QtCore.QCoreApplication.translate
        OWNER_DASHBOARD.setWindowTitle(_translate("OWNER_DASHBOARD", "Form"))
        self.timeLabel.setText(_translate("OWNER_DASHBOARD", " 09 : 10 : 54 AM"))
        self.dateLabel.setText(_translate("OWNER_DASHBOARD", "<html><head/><body><p align=\"center\"><span style=\" font-size:38pt; color:#022162;\">March 1, 2025</span><br/><span style=\" font-size:20pt; color:#b2423c;\">Monday</span></p></body></html>"))
        self.label_4.setText(_translate("OWNER_DASHBOARD", "Today’s Sales"))
        self.label_8.setText(_translate("OWNER_DASHBOARD", "Today’s Total Orders"))
        self.label_10.setText(_translate("OWNER_DASHBOARD", "Best Sellers"))
        self.btnViewSalesReport.setText(_translate("OWNER_DASHBOARD", "View Sales Report"))
        self.label_11.setText(_translate("OWNER_DASHBOARD", "Inventory"))
        self.btnViewMore_Inventory.setText(_translate("OWNER_DASHBOARD", "View More in Inventory"))
        self.label_12.setText(_translate("OWNER_DASHBOARD", "Low in Stock"))
        self.label_13.setText(_translate("OWNER_DASHBOARD", "Warning! These items are low in stock."))
        self.AdminDashboard.setText(_translate("OWNER_DASHBOARD", "Admin Dashboard"))
        self.JJelevate_text_2.setText(_translate("OWNER_DASHBOARD", "J&J "))
        self.pushButton_Dashboard.setText(_translate("OWNER_DASHBOARD", "  Home   "))
        self.pushButton_Inventory.setText(_translate("OWNER_DASHBOARD", "Inventory"))
        self.pushButton_Orders.setText(_translate("OWNER_DASHBOARD", " Orders"))
        self.pushButton_Sales.setText(_translate("OWNER_DASHBOARD", "  Sales"))
        self.pushButton_Account.setText(_translate("OWNER_DASHBOARD", " Account     "))
        self.pushButton_LogOut.setText(_translate("OWNER_DASHBOARD", "   Log out"))
        self.pushButton_Stock_History.setText(_translate("OWNER_DASHBOARD", "Stock History"))
        self.JJelevate_text_3.setText(_translate("OWNER_DASHBOARD", "Elevate"))
