# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/UI_OAccount.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OWNER_ACCOUNT(object):
    def setupUi(self, OWNER_ACCOUNT):
        OWNER_ACCOUNT.setObjectName("OWNER_ACCOUNT")
        OWNER_ACCOUNT.resize(1936, 1005)
        OWNER_ACCOUNT.setStyleSheet("background: white;")
        self.frame = QtWidgets.QFrame(OWNER_ACCOUNT)
        self.frame.setGeometry(QtCore.QRect(299, 209, 1621, 791))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.BUTTONS_FRAME = QtWidgets.QFrame(self.frame)
        self.BUTTONS_FRAME.setGeometry(QtCore.QRect(0, 0, 1621, 61))
        self.BUTTONS_FRAME.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BUTTONS_FRAME.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BUTTONS_FRAME.setObjectName("BUTTONS_FRAME")
        self.pushButton_CREATE_C = QtWidgets.QPushButton(self.BUTTONS_FRAME)
        self.pushButton_CREATE_C.setGeometry(QtCore.QRect(1130, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        self.pushButton_CREATE_C.setFont(font)
        self.pushButton_CREATE_C.setStyleSheet("/* Default Inactive Buttons */\n"
"QPushButton {\n"
"    background-color: #a6a6a6;\n"
"    border-radius: 20px;\n"
"    font-size: 24px;\n"
"    color: #000000;  /* Fixed from font-color to color */\n"
"    padding: 9px;\n"
"    font-family: \"Verdana\", sans-serif; \n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Hover Effect */\n"
"QPushButton:hover {\n"
"    background-color: #374550;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Active Button */\n"
"QPushButton.activeButton {\n"
"    background-color: #374550;\n"
"    color: white;\n"
"}")
        self.pushButton_CREATE_C.setObjectName("pushButton_CREATE_C")
        self.pushButton_VIEW_C = QtWidgets.QPushButton(self.BUTTONS_FRAME)
        self.pushButton_VIEW_C.setGeometry(QtCore.QRect(590, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        self.pushButton_VIEW_C.setFont(font)
        self.pushButton_VIEW_C.setStyleSheet("/* Default Inactive Buttons */\n"
"QPushButton {\n"
"    background-color: #a6a6a6;\n"
"    border-radius: 20px;\n"
"    font-size: 24px;\n"
"    color: #000000;  /* Fixed from font-color to color */\n"
"    padding: 9px;\n"
"    font-family: \"Verdana\", sans-serif; \n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Hover Effect */\n"
"QPushButton:hover {\n"
"    background-color: #374550;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Active Button */\n"
"QPushButton.activeButton {\n"
"    background-color: #374550;\n"
"    color: white;\n"
"}")
        self.pushButton_VIEW_C.setObjectName("pushButton_VIEW_C")
        self.pushButton_VIEW = QtWidgets.QPushButton(self.BUTTONS_FRAME)
        self.pushButton_VIEW.setGeometry(QtCore.QRect(50, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        self.pushButton_VIEW.setFont(font)
        self.pushButton_VIEW.setStyleSheet("/* Default Inactive Buttons */\n"
"QPushButton {\n"
"    background-color: #a6a6a6;\n"
"    border-radius: 20px;\n"
"    font-size: 24px;\n"
"    color: #000000;  /* Fixed from font-color to color */\n"
"    padding: 9px;\n"
"    font-family: \"Verdana\", sans-serif; \n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Hover Effect */\n"
"QPushButton:hover {\n"
"    background-color: #374550;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Active Button */\n"
"QPushButton.activeButton {\n"
"    background-color: #374550;\n"
"    color: white;\n"
"}")
        self.pushButton_VIEW.setObjectName("pushButton_VIEW")
        self.stackedWidget_AccountBtns = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget_AccountBtns.setEnabled(True)
        self.stackedWidget_AccountBtns.setGeometry(QtCore.QRect(-1, 69, 1621, 651))
        self.stackedWidget_AccountBtns.setObjectName("stackedWidget_AccountBtns")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame_4 = QtWidgets.QFrame(self.page)
        self.frame_4.setGeometry(QtCore.QRect(590, -10, 1031, 661))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_41 = QtWidgets.QFrame(self.frame_4)
        self.frame_41.setGeometry(QtCore.QRect(0, 0, 981, 661))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.frame_41.setFont(font)
        self.frame_41.setStyleSheet("background: transparent;")
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.ownerIDText = QtWidgets.QLabel(self.frame_41)
        self.ownerIDText.setGeometry(QtCore.QRect(230, 120, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.ownerIDText.setFont(font)
        self.ownerIDText.setStyleSheet("\n"
"QLabel {\n"
"    font-size:36px;\n"
"}\n"
"    \n"
"")
        self.ownerIDText.setObjectName("ownerIDText")
        self.ownerRoleText = QtWidgets.QLabel(self.frame_41)
        self.ownerRoleText.setGeometry(QtCore.QRect(230, 250, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.ownerRoleText.setFont(font)
        self.ownerRoleText.setStyleSheet("\n"
"QLabel {\n"
"    font-size:36px;\n"
"}\n"
"    \n"
"")
        self.ownerRoleText.setObjectName("ownerRoleText")
        self.ownerNameText = QtWidgets.QLabel(self.frame_41)
        self.ownerNameText.setGeometry(QtCore.QRect(230, 370, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.ownerNameText.setFont(font)
        self.ownerNameText.setStyleSheet("\n"
"QLabel {\n"
"    font-size:36px;\n"
"}\n"
"    \n"
"")
        self.ownerNameText.setObjectName("ownerNameText")
        self.label_3 = QtWidgets.QLabel(self.frame_41)
        self.label_3.setGeometry(QtCore.QRect(-70, 40, 1051, 501))
        self.label_3.setStyleSheet("background-color: rgba(235, 224, 204, 0.47); \n"
"border-radius: 80px;\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.pushButton_EditAccount = QtWidgets.QPushButton(self.frame_41)
        self.pushButton_EditAccount.setGeometry(QtCore.QRect(660, 560, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.pushButton_EditAccount.setFont(font)
        self.pushButton_EditAccount.setStyleSheet("    QPushButton {\n"
"        color: #ffffff;\n"
"        border-radius: 20px;\n"
"        padding: 3px;\n"
"        background-color: #b2423c;\n"
"        font-weight: 500;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgba(178, 66, 60, 0.9);\n"
"    }")
        self.pushButton_EditAccount.setObjectName("pushButton_EditAccount")
        self.ownerID = QtWidgets.QLabel(self.frame_41)
        self.ownerID.setGeometry(QtCore.QRect(230, 160, 551, 51))
        self.ownerID.setStyleSheet("border-radius: 22px; \n"
"font-size: 30px;\n"
"background-color: #ffffff;\n"
"padding: 9px;\n"
"color: #12245c;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"font-size: 25px\n"
"")
        self.ownerID.setText("")
        self.ownerID.setObjectName("ownerID")
        self.ownerRole = QtWidgets.QLabel(self.frame_41)
        self.ownerRole.setGeometry(QtCore.QRect(230, 290, 551, 51))
        self.ownerRole.setStyleSheet("border-radius: 22px; \n"
"font-size: 30px;\n"
"background-color: #ffffff;\n"
"padding: 9px;\n"
"color: #12245c;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"font-size: 25px\n"
"")
        self.ownerRole.setText("")
        self.ownerRole.setObjectName("ownerRole")
        self.ownerName = QtWidgets.QLabel(self.frame_41)
        self.ownerName.setGeometry(QtCore.QRect(230, 410, 551, 51))
        self.ownerName.setStyleSheet("border-radius: 22px; \n"
"font-size: 30px;\n"
"background-color: #ffffff;\n"
"padding: 9px;\n"
"color: #12245c;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"font-size: 25px\n"
"")
        self.ownerName.setText("")
        self.ownerName.setObjectName("ownerName")
        self.label_3.raise_()
        self.ownerIDText.raise_()
        self.ownerRoleText.raise_()
        self.ownerNameText.raise_()
        self.pushButton_EditAccount.raise_()
        self.ownerID.raise_()
        self.ownerRole.raise_()
        self.ownerName.raise_()
        self.frame_10 = QtWidgets.QFrame(self.page)
        self.frame_10.setGeometry(QtCore.QRect(0, -10, 591, 661))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_createUSER_profile_pic_cashier_4 = QtWidgets.QLabel(self.frame_10)
        self.label_createUSER_profile_pic_cashier_4.setGeometry(QtCore.QRect(100, 80, 400, 400))
        self.label_createUSER_profile_pic_cashier_4.setStyleSheet("border-radius: 200px;   /* half of 400 */\n"
"border: 2px solid #12245c;  /* optional: blue border */\n"
"")
        self.label_createUSER_profile_pic_cashier_4.setText("")
        self.label_createUSER_profile_pic_cashier_4.setPixmap(QtGui.QPixmap("views\\../resources/images/userProfilepicture.png"))
        self.label_createUSER_profile_pic_cashier_4.setScaledContents(True)
        self.label_createUSER_profile_pic_cashier_4.setObjectName("label_createUSER_profile_pic_cashier_4")
        self.label_10 = QtWidgets.QLabel(self.frame_10)
        self.label_10.setGeometry(QtCore.QRect(60, 40, 671, 501))
        self.label_10.setStyleSheet("background-color: rgba(235, 224, 204, 0.47); /* #ebe0cc with 47% opacity */\n"
"border-radius:80px;")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_10.raise_()
        self.label_createUSER_profile_pic_cashier_4.raise_()
        self.stackedWidget_AccountBtns.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.frame_5 = QtWidgets.QFrame(self.page_2)
        self.frame_5.setGeometry(QtCore.QRect(590, -10, 1031, 661))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_42 = QtWidgets.QFrame(self.frame_5)
        self.frame_42.setGeometry(QtCore.QRect(0, 0, 981, 661))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.frame_42.setFont(font)
        self.frame_42.setStyleSheet("background: transparent;")
        self.frame_42.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.userNameText = QtWidgets.QLabel(self.frame_42)
        self.userNameText.setGeometry(QtCore.QRect(160, 130, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.userNameText.setFont(font)
        self.userNameText.setStyleSheet("\n"
"QLabel {\n"
"    font-size:20px;\n"
"}\n"
"    \n"
"")
        self.userNameText.setObjectName("userNameText")
        self.oldPassText = QtWidgets.QLabel(self.frame_42)
        self.oldPassText.setGeometry(QtCore.QRect(160, 300, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.oldPassText.setFont(font)
        self.oldPassText.setStyleSheet("\n"
"QLabel {\n"
"    font-size:20px;\n"
"}\n"
"    \n"
"")
        self.oldPassText.setObjectName("oldPassText")
        self.oldPassEnter = QtWidgets.QLineEdit(self.frame_42)
        self.oldPassEnter.setGeometry(QtCore.QRect(150, 340, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(-1)
        self.oldPassEnter.setFont(font)
        self.oldPassEnter.setStyleSheet("border-radius: 22px; \n"
"font-size: 30px;\n"
"background-color: #ffffff;\n"
"padding: 9px;\n"
"color: #12245c;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"font-size: 25px\n"
"")
        self.oldPassEnter.setText("")
        self.oldPassEnter.setPlaceholderText("")
        self.oldPassEnter.setObjectName("oldPassEnter")
        self.setPassText = QtWidgets.QLabel(self.frame_42)
        self.setPassText.setGeometry(QtCore.QRect(580, 300, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.setPassText.setFont(font)
        self.setPassText.setStyleSheet("\n"
"QLabel {\n"
"    font-size:20px;\n"
"}\n"
"    \n"
"")
        self.setPassText.setObjectName("setPassText")
        self.setPassEnter = QtWidgets.QLineEdit(self.frame_42)
        self.setPassEnter.setGeometry(QtCore.QRect(570, 340, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(-1)
        self.setPassEnter.setFont(font)
        self.setPassEnter.setStyleSheet("border-radius: 22px; \n"
"font-size: 30px;\n"
"background-color: #ffffff;\n"
"padding: 9px;\n"
"color: #12245c;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"font-size: 25px\n"
"")
        self.setPassEnter.setText("")
        self.setPassEnter.setPlaceholderText("")
        self.setPassEnter.setObjectName("setPassEnter")
        self.label_4 = QtWidgets.QLabel(self.frame_42)
        self.label_4.setGeometry(QtCore.QRect(-70, 40, 1051, 501))
        self.label_4.setStyleSheet("background-color: rgba(235, 224, 204, 0.47); \n"
"border-radius: 80px;\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton_saveEditaccount = QtWidgets.QPushButton(self.frame_42)
        self.pushButton_saveEditaccount.setGeometry(QtCore.QRect(720, 560, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.pushButton_saveEditaccount.setFont(font)
        self.pushButton_saveEditaccount.setStyleSheet("    QPushButton {\n"
"        color: #ffffff;\n"
"        border-radius: 20px;\n"
"        padding: 3px;\n"
"        background-color: #12245c;\n"
"        font-weight: 500;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgba(18, 36, 92, 0.9);\n"
"    }")
        self.pushButton_saveEditaccount.setObjectName("pushButton_saveEditaccount")
        self.changeUserNameText = QtWidgets.QLabel(self.frame_42)
        self.changeUserNameText.setGeometry(QtCore.QRect(340, 70, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.changeUserNameText.setFont(font)
        self.changeUserNameText.setStyleSheet("\n"
"QLabel {\n"
"    font-size:36px;\n"
"    font-color: #003366;\n"
"}\n"
"    \n"
"")
        self.changeUserNameText.setObjectName("changeUserNameText")
        self.newUserNameEnter = QtWidgets.QLineEdit(self.frame_42)
        self.newUserNameEnter.setGeometry(QtCore.QRect(570, 170, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(-1)
        self.newUserNameEnter.setFont(font)
        self.newUserNameEnter.setStyleSheet("border-radius: 22px; \n"
"font-size: 30px;\n"
"background-color: #ffffff;\n"
"padding: 9px;\n"
"color: #12245c;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"font-size: 25px\n"
"")
        self.newUserNameEnter.setText("")
        self.newUserNameEnter.setPlaceholderText("")
        self.newUserNameEnter.setObjectName("newUserNameEnter")
        self.newUserNameText = QtWidgets.QLabel(self.frame_42)
        self.newUserNameText.setGeometry(QtCore.QRect(580, 130, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.newUserNameText.setFont(font)
        self.newUserNameText.setStyleSheet("\n"
"QLabel {\n"
"    font-size:20px;\n"
"}\n"
"    \n"
"")
        self.newUserNameText.setObjectName("newUserNameText")
        self.changeUserPassText = QtWidgets.QLabel(self.frame_42)
        self.changeUserPassText.setGeometry(QtCore.QRect(350, 250, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.changeUserPassText.setFont(font)
        self.changeUserPassText.setStyleSheet("\n"
"QLabel {\n"
"    font-size:36px;\n"
"}\n"
"    \n"
"")
        self.changeUserPassText.setObjectName("changeUserPassText")
        self.confirmPassEnter = QtWidgets.QLineEdit(self.frame_42)
        self.confirmPassEnter.setGeometry(QtCore.QRect(150, 450, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(-1)
        self.confirmPassEnter.setFont(font)
        self.confirmPassEnter.setStyleSheet("border-radius: 22px; \n"
"font-size: 30px;\n"
"background-color: #ffffff;\n"
"padding: 9px;\n"
"color: #12245c;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"font-size: 25px\n"
"")
        self.confirmPassEnter.setText("")
        self.confirmPassEnter.setPlaceholderText("")
        self.confirmPassEnter.setObjectName("confirmPassEnter")
        self.confirmPassText = QtWidgets.QLabel(self.frame_42)
        self.confirmPassText.setGeometry(QtCore.QRect(160, 410, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.confirmPassText.setFont(font)
        self.confirmPassText.setStyleSheet("\n"
"QLabel {\n"
"    font-size:20px;\n"
"}\n"
"    \n"
"")
        self.confirmPassText.setObjectName("confirmPassText")
        self.pushButton_cancelEditAccount_owner = QtWidgets.QPushButton(self.frame_42)
        self.pushButton_cancelEditAccount_owner.setGeometry(QtCore.QRect(500, 560, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.pushButton_cancelEditAccount_owner.setFont(font)
        self.pushButton_cancelEditAccount_owner.setStyleSheet("    QPushButton {\n"
"        color: #ffffff;\n"
"        border-radius: 20px;\n"
"        padding: 3px;\n"
"        background-color: #b2423c;\n"
"        font-weight: 500;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgba(178, 66, 60, 0.9);\n"
"    }")
        self.pushButton_cancelEditAccount_owner.setObjectName("pushButton_cancelEditAccount_owner")
        self.userNameEnter = QtWidgets.QLabel(self.frame_42)
        self.userNameEnter.setGeometry(QtCore.QRect(150, 170, 341, 51))
        self.userNameEnter.setStyleSheet("border-radius: 22px; \n"
"font-size: 30px;\n"
"background-color: #ffffff;\n"
"padding: 9px;\n"
"color: #12245c;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"font-size: 25px\n"
"")
        self.userNameEnter.setText("")
        self.userNameEnter.setObjectName("userNameEnter")
        self.btn_toggle_old = QtWidgets.QPushButton(self.frame_42)
        self.btn_toggle_old.setGeometry(QtCore.QRect(420, 350, 51, 31))
        self.btn_toggle_old.setStyleSheet("QPushButton#togglePasswordButton {\n"
"    border: none;          /* Removes the border */\n"
"    background-color: transparent; /* Transparent background */\n"
"    padding: 2px;          /* Optional: Adds a bit of spacing */\n"
"}\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("views\\../../../Downloads/EYE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_toggle_old.setIcon(icon)
        self.btn_toggle_old.setIconSize(QtCore.QSize(45, 45))
        self.btn_toggle_old.setObjectName("btn_toggle_old")
        self.btn_toggle_new = QtWidgets.QPushButton(self.frame_42)
        self.btn_toggle_new.setGeometry(QtCore.QRect(840, 350, 51, 31))
        self.btn_toggle_new.setStyleSheet("QPushButton#togglePasswordButton {\n"
"    border: none;          /* Removes the border */\n"
"    background-color: transparent; /* Transparent background */\n"
"    padding: 2px;          /* Optional: Adds a bit of spacing */\n"
"}\n"
"\n"
"")
        self.btn_toggle_new.setIcon(icon)
        self.btn_toggle_new.setIconSize(QtCore.QSize(45, 45))
        self.btn_toggle_new.setObjectName("btn_toggle_new")
        self.btn_toggle_confirm = QtWidgets.QPushButton(self.frame_42)
        self.btn_toggle_confirm.setGeometry(QtCore.QRect(420, 460, 51, 31))
        self.btn_toggle_confirm.setStyleSheet("QPushButton#togglePasswordButton {\n"
"    border: none;          /* Removes the border */\n"
"    background-color: transparent; /* Transparent background */\n"
"    padding: 2px;          /* Optional: Adds a bit of spacing */\n"
"}\n"
"\n"
"")
        self.btn_toggle_confirm.setIcon(icon)
        self.btn_toggle_confirm.setIconSize(QtCore.QSize(45, 45))
        self.btn_toggle_confirm.setObjectName("btn_toggle_confirm")
        self.label_4.raise_()
        self.userNameText.raise_()
        self.oldPassText.raise_()
        self.oldPassEnter.raise_()
        self.setPassText.raise_()
        self.setPassEnter.raise_()
        self.pushButton_saveEditaccount.raise_()
        self.changeUserNameText.raise_()
        self.newUserNameEnter.raise_()
        self.newUserNameText.raise_()
        self.changeUserPassText.raise_()
        self.confirmPassEnter.raise_()
        self.confirmPassText.raise_()
        self.pushButton_cancelEditAccount_owner.raise_()
        self.userNameEnter.raise_()
        self.btn_toggle_old.raise_()
        self.btn_toggle_new.raise_()
        self.btn_toggle_confirm.raise_()
        self.frame_11 = QtWidgets.QFrame(self.page_2)
        self.frame_11.setGeometry(QtCore.QRect(0, -10, 591, 661))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_createUSER_profile_pic_cashier_5 = QtWidgets.QLabel(self.frame_11)
        self.label_createUSER_profile_pic_cashier_5.setGeometry(QtCore.QRect(100, 80, 400, 400))
        self.label_createUSER_profile_pic_cashier_5.setStyleSheet("border-radius: 200px;   /* half of 400 */\n"
"border: 2px solid #12245c;  /* optional: blue border */\n"
"")
        self.label_createUSER_profile_pic_cashier_5.setText("")
        self.label_createUSER_profile_pic_cashier_5.setPixmap(QtGui.QPixmap("views\\../resources/images/userProfilepicture.png"))
        self.label_createUSER_profile_pic_cashier_5.setScaledContents(True)
        self.label_createUSER_profile_pic_cashier_5.setObjectName("label_createUSER_profile_pic_cashier_5")
        self.label_12 = QtWidgets.QLabel(self.frame_11)
        self.label_12.setGeometry(QtCore.QRect(60, 40, 671, 501))
        self.label_12.setStyleSheet("background-color: rgba(235, 224, 204, 0.47); /* #ebe0cc with 47% opacity */\n"
"border-radius:80px;")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_12.raise_()
        self.label_createUSER_profile_pic_cashier_5.raise_()
        self.stackedWidget_AccountBtns.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.frame_6 = QtWidgets.QFrame(self.page_3)
        self.frame_6.setGeometry(QtCore.QRect(590, -10, 1031, 661))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_43 = QtWidgets.QFrame(self.frame_6)
        self.frame_43.setGeometry(QtCore.QRect(0, 0, 981, 661))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.frame_43.setFont(font)
        self.frame_43.setStyleSheet("background: transparent;")
        self.frame_43.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_43.setObjectName("frame_43")
        self.cashierIDText = QtWidgets.QLabel(self.frame_43)
        self.cashierIDText.setGeometry(QtCore.QRect(230, 120, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.cashierIDText.setFont(font)
        self.cashierIDText.setStyleSheet("\n"
"QLabel {\n"
"    font-size:36px;\n"
"}\n"
"    \n"
"")
        self.cashierIDText.setObjectName("cashierIDText")
        self.cashierRoleText = QtWidgets.QLabel(self.frame_43)
        self.cashierRoleText.setGeometry(QtCore.QRect(230, 250, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.cashierRoleText.setFont(font)
        self.cashierRoleText.setStyleSheet("\n"
"QLabel {\n"
"    font-size:36px;\n"
"}\n"
"    \n"
"")
        self.cashierRoleText.setObjectName("cashierRoleText")
        self.cashierNameText = QtWidgets.QLabel(self.frame_43)
        self.cashierNameText.setGeometry(QtCore.QRect(230, 370, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.cashierNameText.setFont(font)
        self.cashierNameText.setStyleSheet("\n"
"QLabel {\n"
"    font-size:36px;\n"
"}\n"
"    \n"
"")
        self.cashierNameText.setObjectName("cashierNameText")
        self.label_5 = QtWidgets.QLabel(self.frame_43)
        self.label_5.setGeometry(QtCore.QRect(-70, 40, 1051, 501))
        self.label_5.setStyleSheet("background-color: rgba(235, 224, 204, 0.47); \n"
"border-radius: 80px;\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.pushButton_EditAccount_cashier = QtWidgets.QPushButton(self.frame_43)
        self.pushButton_EditAccount_cashier.setGeometry(QtCore.QRect(660, 560, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.pushButton_EditAccount_cashier.setFont(font)
        self.pushButton_EditAccount_cashier.setStyleSheet("    QPushButton {\n"
"        color: #ffffff;\n"
"        border-radius: 20px;\n"
"        padding: 3px;\n"
"        background-color: #b2423c;\n"
"        font-weight: 500;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgba(178, 66, 60, 0.9);\n"
"    }")
        self.pushButton_EditAccount_cashier.setObjectName("pushButton_EditAccount_cashier")
        self.cashierID = QtWidgets.QLabel(self.frame_43)
        self.cashierID.setGeometry(QtCore.QRect(230, 160, 561, 51))
        self.cashierID.setStyleSheet("border-radius: 22px; \n"
"font-size: 30px;\n"
"background-color: #ffffff;\n"
"padding: 9px;\n"
"color: #12245c;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"font-size: 25px\n"
"")
        self.cashierID.setText("")
        self.cashierID.setObjectName("cashierID")
        self.cashierRole = QtWidgets.QLabel(self.frame_43)
        self.cashierRole.setGeometry(QtCore.QRect(230, 290, 561, 51))
        self.cashierRole.setStyleSheet("border-radius: 22px; \n"
"font-size: 30px;\n"
"background-color: #ffffff;\n"
"padding: 9px;\n"
"color: #12245c;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"font-size: 25px\n"
"")
        self.cashierRole.setText("")
        self.cashierRole.setObjectName("cashierRole")
        self.cashierName_2 = QtWidgets.QLabel(self.frame_43)
        self.cashierName_2.setGeometry(QtCore.QRect(230, 410, 561, 51))
        self.cashierName_2.setStyleSheet("border-radius: 22px; \n"
"font-size: 30px;\n"
"background-color: #ffffff;\n"
"padding: 9px;\n"
"color: #12245c;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"font-size: 25px\n"
"")
        self.cashierName_2.setText("")
        self.cashierName_2.setObjectName("cashierName_2")
        self.label_5.raise_()
        self.cashierIDText.raise_()
        self.cashierRoleText.raise_()
        self.cashierNameText.raise_()
        self.pushButton_EditAccount_cashier.raise_()
        self.cashierID.raise_()
        self.cashierRole.raise_()
        self.cashierName_2.raise_()
        self.frame_8 = QtWidgets.QFrame(self.page_3)
        self.frame_8.setGeometry(QtCore.QRect(0, -10, 591, 661))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_createUSER_profile_pic_cashier_2 = QtWidgets.QLabel(self.frame_8)
        self.label_createUSER_profile_pic_cashier_2.setGeometry(QtCore.QRect(100, 80, 400, 400))
        self.label_createUSER_profile_pic_cashier_2.setStyleSheet("border-radius: 200px;   /* half of 400 */\n"
"border: 2px solid #12245c;  /* optional: blue border */\n"
"")
        self.label_createUSER_profile_pic_cashier_2.setText("")
        self.label_createUSER_profile_pic_cashier_2.setPixmap(QtGui.QPixmap("views\\../resources/images/userProfilepicture.png"))
        self.label_createUSER_profile_pic_cashier_2.setScaledContents(True)
        self.label_createUSER_profile_pic_cashier_2.setObjectName("label_createUSER_profile_pic_cashier_2")
        self.label_8 = QtWidgets.QLabel(self.frame_8)
        self.label_8.setGeometry(QtCore.QRect(60, 40, 671, 501))
        self.label_8.setStyleSheet("background-color: rgba(235, 224, 204, 0.47); /* #ebe0cc with 47% opacity */\n"
"border-radius:80px;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_8.raise_()
        self.label_createUSER_profile_pic_cashier_2.raise_()
        self.stackedWidget_AccountBtns.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.frame_7 = QtWidgets.QFrame(self.page_4)
        self.frame_7.setGeometry(QtCore.QRect(590, -10, 1031, 661))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_44 = QtWidgets.QFrame(self.frame_7)
        self.frame_44.setGeometry(QtCore.QRect(0, 0, 981, 661))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.frame_44.setFont(font)
        self.frame_44.setStyleSheet("background: transparent;")
        self.frame_44.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_44.setObjectName("frame_44")
        self.userNameText_2 = QtWidgets.QLabel(self.frame_44)
        self.userNameText_2.setGeometry(QtCore.QRect(160, 130, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.userNameText_2.setFont(font)
        self.userNameText_2.setStyleSheet("\n"
"QLabel {\n"
"    font-size:20px;\n"
"}\n"
"    \n"
"")
        self.userNameText_2.setObjectName("userNameText_2")
        self.oldPassText_2 = QtWidgets.QLabel(self.frame_44)
        self.oldPassText_2.setGeometry(QtCore.QRect(160, 300, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.oldPassText_2.setFont(font)
        self.oldPassText_2.setStyleSheet("\n"
"QLabel {\n"
"    font-size:20px;\n"
"}\n"
"    \n"
"")
        self.oldPassText_2.setObjectName("oldPassText_2")
        self.oldPassEnter_2 = QtWidgets.QLineEdit(self.frame_44)
        self.oldPassEnter_2.setGeometry(QtCore.QRect(150, 340, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.oldPassEnter_2.setFont(font)
        self.oldPassEnter_2.setStyleSheet("border: 1px solid #000000; \n"
"border-radius: 22px; \n"
"padding: 1px;")
        self.oldPassEnter_2.setText("")
        self.oldPassEnter_2.setPlaceholderText("")
        self.oldPassEnter_2.setObjectName("oldPassEnter_2")
        self.setPassText_2 = QtWidgets.QLabel(self.frame_44)
        self.setPassText_2.setGeometry(QtCore.QRect(580, 300, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.setPassText_2.setFont(font)
        self.setPassText_2.setStyleSheet("\n"
"QLabel {\n"
"    font-size:20px;\n"
"}\n"
"    \n"
"")
        self.setPassText_2.setObjectName("setPassText_2")
        self.setPassEnter_2 = QtWidgets.QLineEdit(self.frame_44)
        self.setPassEnter_2.setGeometry(QtCore.QRect(570, 340, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.setPassEnter_2.setFont(font)
        self.setPassEnter_2.setStyleSheet("border: 1px solid #000000; \n"
"border-radius: 22px; \n"
"padding: 1px;")
        self.setPassEnter_2.setText("")
        self.setPassEnter_2.setPlaceholderText("")
        self.setPassEnter_2.setObjectName("setPassEnter_2")
        self.label_6 = QtWidgets.QLabel(self.frame_44)
        self.label_6.setGeometry(QtCore.QRect(-70, 40, 1051, 501))
        self.label_6.setStyleSheet("background-color: rgba(235, 224, 204, 0.47); \n"
"border-radius: 80px;\n"
"")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.pushButton_saveEditaccount_cashier = QtWidgets.QPushButton(self.frame_44)
        self.pushButton_saveEditaccount_cashier.setGeometry(QtCore.QRect(720, 560, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.pushButton_saveEditaccount_cashier.setFont(font)
        self.pushButton_saveEditaccount_cashier.setStyleSheet("    QPushButton {\n"
"        color: #ffffff;\n"
"        border-radius: 20px;\n"
"        padding: 3px;\n"
"        background-color: #12245c;\n"
"        font-weight: 500;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgba(18, 36, 92, 0.9);\n"
"    }")
        self.pushButton_saveEditaccount_cashier.setObjectName("pushButton_saveEditaccount_cashier")
        self.changeUserNameText_2 = QtWidgets.QLabel(self.frame_44)
        self.changeUserNameText_2.setGeometry(QtCore.QRect(340, 70, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.changeUserNameText_2.setFont(font)
        self.changeUserNameText_2.setStyleSheet("\n"
"QLabel {\n"
"    font-size:36px;\n"
"    font-color: #003366;\n"
"}\n"
"    \n"
"")
        self.changeUserNameText_2.setObjectName("changeUserNameText_2")
        self.newUserNameEnter_2 = QtWidgets.QLineEdit(self.frame_44)
        self.newUserNameEnter_2.setGeometry(QtCore.QRect(570, 170, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.newUserNameEnter_2.setFont(font)
        self.newUserNameEnter_2.setStyleSheet("border: 1px solid #000000; \n"
"border-radius: 22px; \n"
"padding: 1px;")
        self.newUserNameEnter_2.setText("")
        self.newUserNameEnter_2.setPlaceholderText("")
        self.newUserNameEnter_2.setObjectName("newUserNameEnter_2")
        self.newUserNameText_2 = QtWidgets.QLabel(self.frame_44)
        self.newUserNameText_2.setGeometry(QtCore.QRect(580, 130, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.newUserNameText_2.setFont(font)
        self.newUserNameText_2.setStyleSheet("\n"
"QLabel {\n"
"    font-size:20px;\n"
"}\n"
"    \n"
"")
        self.newUserNameText_2.setObjectName("newUserNameText_2")
        self.changeUserPassText_2 = QtWidgets.QLabel(self.frame_44)
        self.changeUserPassText_2.setGeometry(QtCore.QRect(350, 250, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.changeUserPassText_2.setFont(font)
        self.changeUserPassText_2.setStyleSheet("\n"
"QLabel {\n"
"    font-size:36px;\n"
"}\n"
"    \n"
"")
        self.changeUserPassText_2.setObjectName("changeUserPassText_2")
        self.confirmPassEnter_2 = QtWidgets.QLineEdit(self.frame_44)
        self.confirmPassEnter_2.setGeometry(QtCore.QRect(150, 450, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.confirmPassEnter_2.setFont(font)
        self.confirmPassEnter_2.setStyleSheet("border: 1px solid #000000; \n"
"border-radius: 22px; \n"
"padding: 1px;")
        self.confirmPassEnter_2.setText("")
        self.confirmPassEnter_2.setPlaceholderText("")
        self.confirmPassEnter_2.setObjectName("confirmPassEnter_2")
        self.confirmPassText_2 = QtWidgets.QLabel(self.frame_44)
        self.confirmPassText_2.setGeometry(QtCore.QRect(160, 410, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.confirmPassText_2.setFont(font)
        self.confirmPassText_2.setStyleSheet("\n"
"QLabel {\n"
"    font-size:20px;\n"
"}\n"
"    \n"
"")
        self.confirmPassText_2.setObjectName("confirmPassText_2")
        self.pushButton_cancelEditAccount_cashier = QtWidgets.QPushButton(self.frame_44)
        self.pushButton_cancelEditAccount_cashier.setGeometry(QtCore.QRect(490, 560, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.pushButton_cancelEditAccount_cashier.setFont(font)
        self.pushButton_cancelEditAccount_cashier.setStyleSheet("    QPushButton {\n"
"        color: #ffffff;\n"
"        border-radius: 20px;\n"
"        padding: 3px;\n"
"        background-color: #b2423c;\n"
"        font-weight: 500;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgba(178, 66, 60, 0.9);\n"
"    }")
        self.pushButton_cancelEditAccount_cashier.setObjectName("pushButton_cancelEditAccount_cashier")
        self.userNameEnter_2 = QtWidgets.QLabel(self.frame_44)
        self.userNameEnter_2.setGeometry(QtCore.QRect(150, 170, 341, 51))
        self.userNameEnter_2.setStyleSheet("border: 1px solid #000000; \n"
"border-radius: 22px; \n"
"padding: 1px;")
        self.userNameEnter_2.setText("")
        self.userNameEnter_2.setObjectName("userNameEnter_2")
        self.btn_toggle_old_2 = QtWidgets.QPushButton(self.frame_44)
        self.btn_toggle_old_2.setGeometry(QtCore.QRect(420, 350, 51, 31))
        self.btn_toggle_old_2.setStyleSheet("QPushButton#togglePasswordButton {\n"
"    border: none;          /* Removes the border */\n"
"    background-color: transparent; /* Transparent background */\n"
"    padding: 2px;          /* Optional: Adds a bit of spacing */\n"
"}\n"
"\n"
"")
        self.btn_toggle_old_2.setIcon(icon)
        self.btn_toggle_old_2.setIconSize(QtCore.QSize(45, 45))
        self.btn_toggle_old_2.setObjectName("btn_toggle_old_2")
        self.btn_toggle_new_2 = QtWidgets.QPushButton(self.frame_44)
        self.btn_toggle_new_2.setGeometry(QtCore.QRect(850, 350, 41, 31))
        self.btn_toggle_new_2.setStyleSheet("QPushButton#togglePasswordButton {\n"
"    border: none;          /* Removes the border */\n"
"    background-color: transparent; /* Transparent background */\n"
"    padding: 2px;          /* Optional: Adds a bit of spacing */\n"
"}\n"
"\n"
"")
        self.btn_toggle_new_2.setIcon(icon)
        self.btn_toggle_new_2.setIconSize(QtCore.QSize(45, 45))
        self.btn_toggle_new_2.setObjectName("btn_toggle_new_2")
        self.btn_toggle_confirm_2 = QtWidgets.QPushButton(self.frame_44)
        self.btn_toggle_confirm_2.setGeometry(QtCore.QRect(430, 460, 41, 31))
        self.btn_toggle_confirm_2.setStyleSheet("QPushButton#togglePasswordButton {\n"
"    border: none;          /* Removes the border */\n"
"    background-color: transparent; /* Transparent background */\n"
"    padding: 2px;          /* Optional: Adds a bit of spacing */\n"
"}\n"
"\n"
"")
        self.btn_toggle_confirm_2.setIcon(icon)
        self.btn_toggle_confirm_2.setIconSize(QtCore.QSize(45, 45))
        self.btn_toggle_confirm_2.setObjectName("btn_toggle_confirm_2")
        self.label_6.raise_()
        self.userNameText_2.raise_()
        self.oldPassText_2.raise_()
        self.oldPassEnter_2.raise_()
        self.setPassText_2.raise_()
        self.setPassEnter_2.raise_()
        self.pushButton_saveEditaccount_cashier.raise_()
        self.changeUserNameText_2.raise_()
        self.newUserNameEnter_2.raise_()
        self.newUserNameText_2.raise_()
        self.changeUserPassText_2.raise_()
        self.confirmPassEnter_2.raise_()
        self.confirmPassText_2.raise_()
        self.pushButton_cancelEditAccount_cashier.raise_()
        self.userNameEnter_2.raise_()
        self.btn_toggle_old_2.raise_()
        self.btn_toggle_new_2.raise_()
        self.btn_toggle_confirm_2.raise_()
        self.frame_3 = QtWidgets.QFrame(self.page_4)
        self.frame_3.setGeometry(QtCore.QRect(0, -10, 591, 661))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_createUSER_profile_pic_cashier = QtWidgets.QLabel(self.frame_3)
        self.label_createUSER_profile_pic_cashier.setGeometry(QtCore.QRect(100, 80, 400, 400))
        self.label_createUSER_profile_pic_cashier.setStyleSheet("border-radius: 200px;   /* half of 400 */\n"
"border: 2px solid #12245c;  /* optional: blue border */\n"
"")
        self.label_createUSER_profile_pic_cashier.setText("")
        self.label_createUSER_profile_pic_cashier.setPixmap(QtGui.QPixmap("views\\../resources/images/userProfilepicture.png"))
        self.label_createUSER_profile_pic_cashier.setScaledContents(True)
        self.label_createUSER_profile_pic_cashier.setObjectName("label_createUSER_profile_pic_cashier")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(60, 40, 671, 501))
        self.label_2.setStyleSheet("background-color: rgba(235, 224, 204, 0.47); /* #ebe0cc with 47% opacity */\n"
"border-radius:80px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.label_createUSER_profile_pic_cashier.raise_()
        self.stackedWidget_AccountBtns.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_11 = QtWidgets.QLabel(self.page_5)
        self.label_11.setGeometry(QtCore.QRect(50, 30, 1521, 501))
        self.label_11.setStyleSheet("background-color: rgba(235, 224, 204, 0.47); \n"
"border-radius: 40px;\n"
"")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.changeUserNameText_3 = QtWidgets.QLabel(self.page_5)
        self.changeUserNameText_3.setGeometry(QtCore.QRect(100, 90, 631, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.changeUserNameText_3.setFont(font)
        self.changeUserNameText_3.setAutoFillBackground(False)
        self.changeUserNameText_3.setStyleSheet("\n"
"QLabel {\n"
"    background: transparent;\n"
"    font-size: 40px;\n"
"    font-color: #003366;\n"
"}\n"
"    \n"
"")
        self.changeUserNameText_3.setObjectName("changeUserNameText_3")
        self.changeUserNameText_4 = QtWidgets.QLabel(self.page_5)
        self.changeUserNameText_4.setGeometry(QtCore.QRect(190, 200, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.changeUserNameText_4.setFont(font)
        self.changeUserNameText_4.setAutoFillBackground(False)
        self.changeUserNameText_4.setStyleSheet("\n"
"QLabel {\n"
"    background: transparent;\n"
"    font-size:22px;\n"
"    font-color: #003366;\n"
"}\n"
"    \n"
"")
        self.changeUserNameText_4.setObjectName("changeUserNameText_4")
        self.changeUserNameText_5 = QtWidgets.QLabel(self.page_5)
        self.changeUserNameText_5.setGeometry(QtCore.QRect(650, 200, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.changeUserNameText_5.setFont(font)
        self.changeUserNameText_5.setAutoFillBackground(False)
        self.changeUserNameText_5.setStyleSheet("\n"
"QLabel {\n"
"    background: transparent;\n"
"    font-size:22px;\n"
"    font-color: #003366;\n"
"}\n"
"    \n"
"")
        self.changeUserNameText_5.setObjectName("changeUserNameText_5")
        self.changeUserNameText_6 = QtWidgets.QLabel(self.page_5)
        self.changeUserNameText_6.setGeometry(QtCore.QRect(1110, 200, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.changeUserNameText_6.setFont(font)
        self.changeUserNameText_6.setAutoFillBackground(False)
        self.changeUserNameText_6.setStyleSheet("\n"
"QLabel {\n"
"    background: transparent;\n"
"    font-size:22px;\n"
"    font-color: #003366;\n"
"}\n"
"    \n"
"")
        self.changeUserNameText_6.setObjectName("changeUserNameText_6")
        self.shopIDCashier = QtWidgets.QLineEdit(self.page_5)
        self.shopIDCashier.setGeometry(QtCore.QRect(180, 250, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.shopIDCashier.setFont(font)
        self.shopIDCashier.setStyleSheet("border: 1px solid #000000; \n"
"border-radius: 22px; \n"
"padding: 1px;")
        self.shopIDCashier.setText("")
        self.shopIDCashier.setPlaceholderText("")
        self.shopIDCashier.setObjectName("shopIDCashier")
        self.createAccRole = QtWidgets.QLineEdit(self.page_5)
        self.createAccRole.setGeometry(QtCore.QRect(640, 250, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.createAccRole.setFont(font)
        self.createAccRole.setStyleSheet("border: 1px solid #000000; \n"
"border-radius: 22px; \n"
"padding: 1px;")
        self.createAccRole.setText("")
        self.createAccRole.setPlaceholderText("")
        self.createAccRole.setObjectName("createAccRole")
        self.createAccName = QtWidgets.QLineEdit(self.page_5)
        self.createAccName.setGeometry(QtCore.QRect(1100, 250, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.createAccName.setFont(font)
        self.createAccName.setStyleSheet("border: 1px solid #000000; \n"
"border-radius: 22px; \n"
"padding: 1px;")
        self.createAccName.setText("")
        self.createAccName.setPlaceholderText("")
        self.createAccName.setObjectName("createAccName")
        self.createAccPass = QtWidgets.QLineEdit(self.page_5)
        self.createAccPass.setGeometry(QtCore.QRect(180, 380, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.createAccPass.setFont(font)
        self.createAccPass.setStyleSheet("border: 1px solid #000000; \n"
"border-radius: 22px; \n"
"padding: 1px;")
        self.createAccPass.setText("")
        self.createAccPass.setPlaceholderText("")
        self.createAccPass.setObjectName("createAccPass")
        self.changeUserNameText_7 = QtWidgets.QLabel(self.page_5)
        self.changeUserNameText_7.setGeometry(QtCore.QRect(190, 330, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.changeUserNameText_7.setFont(font)
        self.changeUserNameText_7.setAutoFillBackground(False)
        self.changeUserNameText_7.setStyleSheet("\n"
"QLabel {\n"
"    background: transparent;\n"
"    font-size:22px;\n"
"    font-color: #003366;\n"
"}\n"
"    \n"
"")
        self.changeUserNameText_7.setObjectName("changeUserNameText_7")
        self.createAccConfrimPass = QtWidgets.QLineEdit(self.page_5)
        self.createAccConfrimPass.setGeometry(QtCore.QRect(640, 380, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.createAccConfrimPass.setFont(font)
        self.createAccConfrimPass.setStyleSheet("border: 1px solid #000000; \n"
"border-radius: 22px; \n"
"padding: 1px;")
        self.createAccConfrimPass.setText("")
        self.createAccConfrimPass.setPlaceholderText("")
        self.createAccConfrimPass.setObjectName("createAccConfrimPass")
        self.changeUserNameText_8 = QtWidgets.QLabel(self.page_5)
        self.changeUserNameText_8.setGeometry(QtCore.QRect(650, 330, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.changeUserNameText_8.setFont(font)
        self.changeUserNameText_8.setAutoFillBackground(False)
        self.changeUserNameText_8.setStyleSheet("\n"
"QLabel {\n"
"    background: transparent;\n"
"    font-size:22px;\n"
"    font-color: #003366;\n"
"}\n"
"    \n"
"")
        self.changeUserNameText_8.setObjectName("changeUserNameText_8")
        self.pushButton_CreateAccount_cashier = QtWidgets.QPushButton(self.page_5)
        self.pushButton_CreateAccount_cashier.setGeometry(QtCore.QRect(1360, 550, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.pushButton_CreateAccount_cashier.setFont(font)
        self.pushButton_CreateAccount_cashier.setStyleSheet("    QPushButton {\n"
"        color: #ffffff;\n"
"        border-radius: 20px;\n"
"        padding: 3px;\n"
"        background-color: #12245c;\n"
"        font-weight: 500;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgba(18, 36, 92, 0.9);\n"
"    }")
        self.pushButton_CreateAccount_cashier.setObjectName("pushButton_CreateAccount_cashier")
        self.pushButton_cancelCreateAccount_cashier = QtWidgets.QPushButton(self.page_5)
        self.pushButton_cancelCreateAccount_cashier.setGeometry(QtCore.QRect(1140, 550, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(62)
        self.pushButton_cancelCreateAccount_cashier.setFont(font)
        self.pushButton_cancelCreateAccount_cashier.setStyleSheet("    QPushButton {\n"
"        color: #ffffff;\n"
"        border-radius: 20px;\n"
"        padding: 3px;\n"
"        background-color: #b2423c;\n"
"        font-weight: 500;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgba(178, 66, 60, 0.9);\n"
"    }")
        self.pushButton_cancelCreateAccount_cashier.setObjectName("pushButton_cancelCreateAccount_cashier")
        self.stackedWidget_AccountBtns.addWidget(self.page_5)
        self.frame_45 = QtWidgets.QFrame(OWNER_ACCOUNT)
        self.frame_45.setGeometry(QtCore.QRect(300, 0, 1621, 211))
        self.frame_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.timeLabel = QtWidgets.QLabel(self.frame_45)
        self.timeLabel.setGeometry(QtCore.QRect(840, 20, 731, 171))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.timeLabel.setFont(font)
        self.timeLabel.setStyleSheet("\n"
"    background-color: #f6f3ee;\n"
"    border-radius: 16;\n"
"    padding: 10px;\n"
"color: #051a54;\n"
"")
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.dateLabel = QtWidgets.QLabel(self.frame_45)
        self.dateLabel.setGeometry(QtCore.QRect(40, 20, 771, 171))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setBold(True)
        font.setWeight(75)
        self.dateLabel.setFont(font)
        self.dateLabel.setStyleSheet("\n"
"    background-color: #f6f3ee;\n"
"    border-radius: 16;\n"
"    padding: 10px;\n"
"\n"
"")
        self.dateLabel.setTextFormat(QtCore.Qt.RichText)
        self.dateLabel.setObjectName("dateLabel")
        self.label = QtWidgets.QLabel(OWNER_ACCOUNT)
        self.label.setGeometry(QtCore.QRect(300, 930, 1631, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: #374550;\n"
"padding: 2px;\n"
"color: #ffffff;\n"
"text-align: center;\n"
"")
        self.label.setObjectName("label")
        self.LeftMenuBar = QtWidgets.QFrame(OWNER_ACCOUNT)
        self.LeftMenuBar.setGeometry(QtCore.QRect(0, 0, 301, 1011))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LeftMenuBar.setFont(font)
        self.LeftMenuBar.setStyleSheet("background-color: rgba(235, 224, 204, 0.47); /* #ebe0cc with 47% opacity */")
        self.LeftMenuBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LeftMenuBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LeftMenuBar.setObjectName("LeftMenuBar")
        self.JJelevate_text_2 = QtWidgets.QLabel(self.LeftMenuBar)
        self.JJelevate_text_2.setGeometry(QtCore.QRect(60, 220, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.JJelevate_text_2.setFont(font)
        self.JJelevate_text_2.setStyleSheet("color: #12245c;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"background: transparent;\n"
"font-size: 30px;")
        self.JJelevate_text_2.setScaledContents(True)
        self.JJelevate_text_2.setObjectName("JJelevate_text_2")
        self.Logo = QtWidgets.QLabel(self.LeftMenuBar)
        self.Logo.setGeometry(QtCore.QRect(30, 50, 241, 171))
        self.Logo.setStyleSheet("background: transparent;")
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("views\\../resources/images/JJLOGO.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setAlignment(QtCore.Qt.AlignCenter)
        self.Logo.setObjectName("Logo")
        self.pushButton_Dashboard = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Dashboard.setGeometry(QtCore.QRect(30, 310, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_Dashboard.setFont(font)
        self.pushButton_Dashboard.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("views\\../resources/images/dashboard_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Dashboard.setIcon(icon1)
        self.pushButton_Dashboard.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Dashboard.setObjectName("pushButton_Dashboard")
        self.pushButton_Inventory = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Inventory.setGeometry(QtCore.QRect(30, 390, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Inventory.setFont(font)
        self.pushButton_Inventory.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("views\\../resources/images/inventory_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Inventory.setIcon(icon2)
        self.pushButton_Inventory.setIconSize(QtCore.QSize(50, 45))
        self.pushButton_Inventory.setObjectName("pushButton_Inventory")
        self.pushButton_Orders = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Orders.setGeometry(QtCore.QRect(30, 470, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Orders.setFont(font)
        self.pushButton_Orders.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("views\\../resources/images/orders_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Orders.setIcon(icon3)
        self.pushButton_Orders.setIconSize(QtCore.QSize(46, 42))
        self.pushButton_Orders.setObjectName("pushButton_Orders")
        self.pushButton_Sales = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Sales.setGeometry(QtCore.QRect(30, 550, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Sales.setFont(font)
        self.pushButton_Sales.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("views\\../resources/images/sales_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Sales.setIcon(icon4)
        self.pushButton_Sales.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_Sales.setObjectName("pushButton_Sales")
        self.pushButton_Account = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Account.setGeometry(QtCore.QRect(30, 710, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Account.setFont(font)
        self.pushButton_Account.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("views\\../resources/images/account_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Account.setIcon(icon5)
        self.pushButton_Account.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_Account.setObjectName("pushButton_Account")
        self.pushButton_LogOut = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_LogOut.setGeometry(QtCore.QRect(30, 890, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(87)
        self.pushButton_LogOut.setFont(font)
        self.pushButton_LogOut.setStyleSheet("QPushButton {\n"
"    background-color:#022162;\n"
"color:white;\n"
"font-weight: 700;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"font-size: 14;\n"
"text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"        background-color: rgba(2, 33, 98, 0.8);\n"
"        color: white;\n"
"    font-weight: 700;\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("views\\../resources/images/WHITElogout_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_LogOut.setIcon(icon6)
        self.pushButton_LogOut.setIconSize(QtCore.QSize(38, 38))
        self.pushButton_LogOut.setObjectName("pushButton_LogOut")
        self.pushButton_Stock_History = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Stock_History.setGeometry(QtCore.QRect(30, 630, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Stock_History.setFont(font)
        self.pushButton_Stock_History.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        self.pushButton_Stock_History.setIcon(icon2)
        self.pushButton_Stock_History.setIconSize(QtCore.QSize(50, 45))
        self.pushButton_Stock_History.setObjectName("pushButton_Stock_History")
        self.JJelevate_text_3 = QtWidgets.QLabel(self.LeftMenuBar)
        self.JJelevate_text_3.setGeometry(QtCore.QRect(130, 220, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.JJelevate_text_3.setFont(font)
        self.JJelevate_text_3.setStyleSheet("color: #d75413;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"background: transparent;\n"
"font-size: 29px;\n"
"")
        self.JJelevate_text_3.setScaledContents(True)
        self.JJelevate_text_3.setObjectName("JJelevate_text_3")

        self.retranslateUi(OWNER_ACCOUNT)
        self.stackedWidget_AccountBtns.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(OWNER_ACCOUNT)

    def retranslateUi(self, OWNER_ACCOUNT):
        _translate = QtCore.QCoreApplication.translate
        OWNER_ACCOUNT.setWindowTitle(_translate("OWNER_ACCOUNT", "Form"))
        self.pushButton_CREATE_C.setText(_translate("OWNER_ACCOUNT", "Create New Cashier Account"))
        self.pushButton_VIEW_C.setText(_translate("OWNER_ACCOUNT", "View Cashier Account"))
        self.pushButton_VIEW.setText(_translate("OWNER_ACCOUNT", "View Account"))
        self.ownerIDText.setText(_translate("OWNER_ACCOUNT", "User ID"))
        self.ownerRoleText.setText(_translate("OWNER_ACCOUNT", "User Role"))
        self.ownerNameText.setText(_translate("OWNER_ACCOUNT", "Username"))
        self.pushButton_EditAccount.setText(_translate("OWNER_ACCOUNT", "Edit Details"))
        self.userNameText.setText(_translate("OWNER_ACCOUNT", "Username"))
        self.oldPassText.setText(_translate("OWNER_ACCOUNT", "Old Password"))
        self.setPassText.setText(_translate("OWNER_ACCOUNT", "Set New Password"))
        self.pushButton_saveEditaccount.setText(_translate("OWNER_ACCOUNT", "Save"))
        self.changeUserNameText.setText(_translate("OWNER_ACCOUNT", "Change Username"))
        self.newUserNameText.setText(_translate("OWNER_ACCOUNT", "New Username"))
        self.changeUserPassText.setText(_translate("OWNER_ACCOUNT", "Change Password"))
        self.confirmPassText.setText(_translate("OWNER_ACCOUNT", "Confirm New Password"))
        self.pushButton_cancelEditAccount_owner.setText(_translate("OWNER_ACCOUNT", "Cancel"))
        self.btn_toggle_old.setText(_translate("OWNER_ACCOUNT", "Show"))
        self.btn_toggle_new.setText(_translate("OWNER_ACCOUNT", "Show"))
        self.btn_toggle_confirm.setText(_translate("OWNER_ACCOUNT", "Show"))
        self.cashierIDText.setText(_translate("OWNER_ACCOUNT", "User ID"))
        self.cashierRoleText.setText(_translate("OWNER_ACCOUNT", "User Role"))
        self.cashierNameText.setText(_translate("OWNER_ACCOUNT", "Username"))
        self.pushButton_EditAccount_cashier.setText(_translate("OWNER_ACCOUNT", "Edit Details"))
        self.userNameText_2.setText(_translate("OWNER_ACCOUNT", "Username"))
        self.oldPassText_2.setText(_translate("OWNER_ACCOUNT", "Old Password"))
        self.setPassText_2.setText(_translate("OWNER_ACCOUNT", "Set New Password"))
        self.pushButton_saveEditaccount_cashier.setText(_translate("OWNER_ACCOUNT", "Save"))
        self.changeUserNameText_2.setText(_translate("OWNER_ACCOUNT", "Change Username"))
        self.newUserNameText_2.setText(_translate("OWNER_ACCOUNT", "New Username"))
        self.changeUserPassText_2.setText(_translate("OWNER_ACCOUNT", "Change Password"))
        self.confirmPassText_2.setText(_translate("OWNER_ACCOUNT", "Confirm New Password"))
        self.pushButton_cancelEditAccount_cashier.setText(_translate("OWNER_ACCOUNT", "Cancel"))
        self.btn_toggle_old_2.setText(_translate("OWNER_ACCOUNT", "Show"))
        self.btn_toggle_new_2.setText(_translate("OWNER_ACCOUNT", "Show"))
        self.btn_toggle_confirm_2.setText(_translate("OWNER_ACCOUNT", "Show"))
        self.changeUserNameText_3.setText(_translate("OWNER_ACCOUNT", "Create a New Cashier Account"))
        self.changeUserNameText_4.setText(_translate("OWNER_ACCOUNT", "Shop ID"))
        self.changeUserNameText_5.setText(_translate("OWNER_ACCOUNT", "User Role"))
        self.changeUserNameText_6.setText(_translate("OWNER_ACCOUNT", "Username"))
        self.changeUserNameText_7.setText(_translate("OWNER_ACCOUNT", "Password"))
        self.changeUserNameText_8.setText(_translate("OWNER_ACCOUNT", "Confirm Password"))
        self.pushButton_CreateAccount_cashier.setText(_translate("OWNER_ACCOUNT", "Confirm"))
        self.pushButton_cancelCreateAccount_cashier.setText(_translate("OWNER_ACCOUNT", "Discard"))
        self.timeLabel.setText(_translate("OWNER_ACCOUNT", " 09 : 10 : 54 AM"))
        self.dateLabel.setText(_translate("OWNER_ACCOUNT", "<html><head/><body><p align=\"center\"><span style=\" font-size:38pt; color:#022162;\">March 1, 2025</span><br/><span style=\" font-size:20pt; color:#b2423c;\">Monday</span></p></body></html>"))
        self.label.setText(_translate("OWNER_ACCOUNT", "                                                                           J  &  J  ROOFSTEEL  AND  GUTTER  SUPPLY  (MOALBOAL BRANCH)     "))
        self.JJelevate_text_2.setText(_translate("OWNER_ACCOUNT", "J&J "))
        self.pushButton_Dashboard.setText(_translate("OWNER_ACCOUNT", "  Home   "))
        self.pushButton_Inventory.setText(_translate("OWNER_ACCOUNT", "Inventory"))
        self.pushButton_Orders.setText(_translate("OWNER_ACCOUNT", " Orders"))
        self.pushButton_Sales.setText(_translate("OWNER_ACCOUNT", "  Sales"))
        self.pushButton_Account.setText(_translate("OWNER_ACCOUNT", " Account     "))
        self.pushButton_LogOut.setText(_translate("OWNER_ACCOUNT", "   Log out"))
        self.pushButton_Stock_History.setText(_translate("OWNER_ACCOUNT", "Stock History"))
        self.JJelevate_text_3.setText(_translate("OWNER_ACCOUNT", "Elevate"))
