# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/UI_OStockHistory.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OWNER_STOCKHISTORY(object):
    def setupUi(self, OWNER_STOCKHISTORY):
        OWNER_STOCKHISTORY.setObjectName("OWNER_STOCKHISTORY")
        OWNER_STOCKHISTORY.resize(1921, 1005)
        OWNER_STOCKHISTORY.setStyleSheet("background: white;")
        self.tableWidget_StockHistory = QtWidgets.QTableWidget(OWNER_STOCKHISTORY)
        self.tableWidget_StockHistory.setGeometry(QtCore.QRect(380, 230, 1471, 701))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_StockHistory.setFont(font)
        self.tableWidget_StockHistory.setStyleSheet("QTableWidget {\n"
"    background-color: white;\n"
"    gridline-color: lightgray;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #003366; \n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"    font-size:18px;\n"
"}\n"
"")
        self.tableWidget_StockHistory.setObjectName("tableWidget_StockHistory")
        self.tableWidget_StockHistory.setColumnCount(7)
        self.tableWidget_StockHistory.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_StockHistory.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_StockHistory.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_StockHistory.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_StockHistory.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_StockHistory.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_StockHistory.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_StockHistory.setHorizontalHeaderItem(6, item)
        self.tableWidget_StockHistory.horizontalHeader().setDefaultSectionSize(345)
        self.frame_45 = QtWidgets.QFrame(OWNER_STOCKHISTORY)
        self.frame_45.setGeometry(QtCore.QRect(300, 0, 1641, 231))
        self.frame_45.setStyleSheet("background: transparent;;")
        self.frame_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.comboBox_filterStockHistory = QtWidgets.QComboBox(self.frame_45)
        self.comboBox_filterStockHistory.setGeometry(QtCore.QRect(1350, 50, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.comboBox_filterStockHistory.setFont(font)
        self.comboBox_filterStockHistory.setStyleSheet("    background-color: #ebe0cc;\n"
"    border-radius: 15px;\n"
"font-size:28px;\n"
"text-align: center;")
        self.comboBox_filterStockHistory.setMaxCount(2147483644)
        self.comboBox_filterStockHistory.setObjectName("comboBox_filterStockHistory")
        self.comboBox_filterStockHistory.addItem("")
        self.comboBox_filterStockHistory.addItem("")
        self.comboBox_filterStockHistory.addItem("")
        self.comboBox_filterStockHistory.addItem("")
        self.comboBox_filterStockHistory.addItem("")
        self.frame_4 = QtWidgets.QFrame(self.frame_45)
        self.frame_4.setGeometry(QtCore.QRect(830, 50, 501, 71))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.lineEdit_OWNER_QuickSearch_StockHistory = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_OWNER_QuickSearch_StockHistory.setGeometry(QtCore.QRect(10, 10, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_OWNER_QuickSearch_StockHistory.setFont(font)
        self.lineEdit_OWNER_QuickSearch_StockHistory.setStyleSheet("\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    padding: 2px;\n"
"    text-align: center;\n"
"\n"
"\n"
"\n"
"")
        self.lineEdit_OWNER_QuickSearch_StockHistory.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_OWNER_QuickSearch_StockHistory.setClearButtonEnabled(False)
        self.lineEdit_OWNER_QuickSearch_StockHistory.setObjectName("lineEdit_OWNER_QuickSearch_StockHistory")
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(10, 10, 71, 51))
        self.label_14.setStyleSheet("background: transparent;\n"
"padding: 5;\n"
"")
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("views\\../resources/images/search.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.pushButton_SEARCH_StockHistory = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_SEARCH_StockHistory.setGeometry(QtCore.QRect(300, 10, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_SEARCH_StockHistory.setFont(font)
        self.pushButton_SEARCH_StockHistory.setStyleSheet("    QPushButton {\n"
"        background-color: #003366;\n"
"        color: white;\n"
"        padding: 2px;\n"
"        text-align: center;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgba(0, 51, 102, 0.9);\n"
"    }")
        self.pushButton_SEARCH_StockHistory.setObjectName("pushButton_SEARCH_StockHistory")
        self.stockHistoryText = QtWidgets.QLabel(self.frame_45)
        self.stockHistoryText.setGeometry(QtCore.QRect(40, 50, 801, 71))
        self.stockHistoryText.setStyleSheet("color: #12245c;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"background: transparent;\n"
"font-size: 50px;")
        self.stockHistoryText.setObjectName("stockHistoryText")
        self.pushButton_OWNER_Delete_Stock = QtWidgets.QPushButton(self.frame_45)
        self.pushButton_OWNER_Delete_Stock.setGeometry(QtCore.QRect(1110, 170, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_OWNER_Delete_Stock.setFont(font)
        self.pushButton_OWNER_Delete_Stock.setStyleSheet("/* Default Inactive Action Buttons */\n"
"QPushButton {\n"
"    background-color: #a6a6a6;\n"
"    border-radius: 10px;  /* Added \'px\' unit */\n"
"    color: black;\n"
"    padding: 2px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Hover Effect on Inactive Action Buttons */\n"
"QPushButton:hover {\n"
"    background-color: #c25b55;\n"
"    color: black;\n"
"}\n"
"\n"
"/* Active Action Button */\n"
"QPushButton.activeActionButton {  /* Changed from # to . for class selector */\n"
"    background-color: #c25b55;\n"
"    color: black;\n"
"    /* Maintain same properties as base button */\n"
"    border-radius: 10px;\n"
"    padding: 2px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("views\\../resources/images/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_OWNER_Delete_Stock.setIcon(icon)
        self.pushButton_OWNER_Delete_Stock.setIconSize(QtCore.QSize(27, 27))
        self.pushButton_OWNER_Delete_Stock.setObjectName("pushButton_OWNER_Delete_Stock")
        self.stockHistoryText_2 = QtWidgets.QLabel(self.frame_45)
        self.stockHistoryText_2.setGeometry(QtCore.QRect(80, 160, 801, 61))
        self.stockHistoryText_2.setStyleSheet("color:  #c25b55;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"background: transparent;\n"
"font-size: 36px;")
        self.stockHistoryText_2.setObjectName("stockHistoryText_2")
        self.pushButton_OWNER_Delete_All = QtWidgets.QPushButton(self.frame_45)
        self.pushButton_OWNER_Delete_All.setGeometry(QtCore.QRect(1330, 170, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_OWNER_Delete_All.setFont(font)
        self.pushButton_OWNER_Delete_All.setStyleSheet("/* Default Inactive Action Buttons */\n"
"QPushButton {\n"
"    background-color: #a6a6a6;\n"
"    border-radius: 10px;  /* Added \'px\' unit */\n"
"    color: black;\n"
"    padding: 2px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/* Hover Effect on Inactive Action Buttons */\n"
"QPushButton:hover {\n"
"    background-color: #c25b55;\n"
"    color: black;\n"
"}\n"
"\n"
"/* Active Action Button */\n"
"QPushButton.activeActionButton {  /* Changed from # to . for class selector */\n"
"    background-color: #c25b55;\n"
"    color: black;\n"
"    /* Maintain same properties as base button */\n"
"    border-radius: 10px;\n"
"    padding: 2px;\n"
"}")
        self.pushButton_OWNER_Delete_All.setIcon(icon)
        self.pushButton_OWNER_Delete_All.setIconSize(QtCore.QSize(27, 27))
        self.pushButton_OWNER_Delete_All.setObjectName("pushButton_OWNER_Delete_All")
        self.LeftMenuBar = QtWidgets.QFrame(OWNER_STOCKHISTORY)
        self.LeftMenuBar.setGeometry(QtCore.QRect(0, 0, 301, 1011))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LeftMenuBar.setFont(font)
        self.LeftMenuBar.setStyleSheet("background-color: rgba(235, 224, 204, 0.47); /* #ebe0cc with 47% opacity */")
        self.LeftMenuBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LeftMenuBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LeftMenuBar.setObjectName("LeftMenuBar")
        self.JJelevate_text_2 = QtWidgets.QLabel(self.LeftMenuBar)
        self.JJelevate_text_2.setGeometry(QtCore.QRect(60, 220, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.JJelevate_text_2.setFont(font)
        self.JJelevate_text_2.setStyleSheet("color: #12245c;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"background: transparent;\n"
"font-size: 30px;")
        self.JJelevate_text_2.setScaledContents(True)
        self.JJelevate_text_2.setObjectName("JJelevate_text_2")
        self.Logo = QtWidgets.QLabel(self.LeftMenuBar)
        self.Logo.setGeometry(QtCore.QRect(30, 50, 241, 171))
        self.Logo.setStyleSheet("background: transparent;")
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("views\\../resources/images/JJLOGO.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setAlignment(QtCore.Qt.AlignCenter)
        self.Logo.setObjectName("Logo")
        self.pushButton_Dashboard = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Dashboard.setGeometry(QtCore.QRect(30, 310, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_Dashboard.setFont(font)
        self.pushButton_Dashboard.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("views\\../resources/images/dashboard_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Dashboard.setIcon(icon1)
        self.pushButton_Dashboard.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Dashboard.setObjectName("pushButton_Dashboard")
        self.pushButton_Inventory = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Inventory.setGeometry(QtCore.QRect(30, 390, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Inventory.setFont(font)
        self.pushButton_Inventory.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("views\\../resources/images/inventory_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Inventory.setIcon(icon2)
        self.pushButton_Inventory.setIconSize(QtCore.QSize(50, 45))
        self.pushButton_Inventory.setObjectName("pushButton_Inventory")
        self.pushButton_Orders = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Orders.setGeometry(QtCore.QRect(30, 470, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Orders.setFont(font)
        self.pushButton_Orders.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("views\\../resources/images/orders_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Orders.setIcon(icon3)
        self.pushButton_Orders.setIconSize(QtCore.QSize(46, 42))
        self.pushButton_Orders.setObjectName("pushButton_Orders")
        self.pushButton_Sales = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Sales.setGeometry(QtCore.QRect(30, 550, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Sales.setFont(font)
        self.pushButton_Sales.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("views\\../resources/images/sales_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Sales.setIcon(icon4)
        self.pushButton_Sales.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_Sales.setObjectName("pushButton_Sales")
        self.pushButton_Account = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Account.setGeometry(QtCore.QRect(30, 710, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Account.setFont(font)
        self.pushButton_Account.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("views\\../resources/images/account_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Account.setIcon(icon5)
        self.pushButton_Account.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_Account.setObjectName("pushButton_Account")
        self.pushButton_LogOut = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_LogOut.setGeometry(QtCore.QRect(30, 890, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(87)
        self.pushButton_LogOut.setFont(font)
        self.pushButton_LogOut.setStyleSheet("QPushButton {\n"
"    background-color:#022162;\n"
"color:white;\n"
"font-weight: 700;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"font-size: 14;\n"
"text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"        background-color: rgba(2, 33, 98, 0.8);\n"
"        color: white;\n"
"    font-weight: 700;\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("views\\../resources/images/WHITElogout_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_LogOut.setIcon(icon6)
        self.pushButton_LogOut.setIconSize(QtCore.QSize(38, 38))
        self.pushButton_LogOut.setObjectName("pushButton_LogOut")
        self.pushButton_Stock_History = QtWidgets.QPushButton(self.LeftMenuBar)
        self.pushButton_Stock_History.setGeometry(QtCore.QRect(30, 630, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.pushButton_Stock_History.setFont(font)
        self.pushButton_Stock_History.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 25px;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton.activeButton {\n"
"    background-color:#c25b55;\n"
"    color:black;\n"
"    font-weight: 700;\n"
"}\n"
"")
        self.pushButton_Stock_History.setIcon(icon2)
        self.pushButton_Stock_History.setIconSize(QtCore.QSize(50, 45))
        self.pushButton_Stock_History.setObjectName("pushButton_Stock_History")
        self.JJelevate_text_3 = QtWidgets.QLabel(self.LeftMenuBar)
        self.JJelevate_text_3.setGeometry(QtCore.QRect(130, 220, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.JJelevate_text_3.setFont(font)
        self.JJelevate_text_3.setStyleSheet("color: #d75413;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"background: transparent;\n"
"font-size: 29px;\n"
"")
        self.JJelevate_text_3.setScaledContents(True)
        self.JJelevate_text_3.setObjectName("JJelevate_text_3")
        self.label_13 = QtWidgets.QLabel(OWNER_STOCKHISTORY)
        self.label_13.setGeometry(QtCore.QRect(340, 150, 1541, 821))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        font.setItalic(True)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet(" background-color: #f6f3ee;\n"
"    border-radius: 16;\n"
"    padding: 10px;\n"
"")
        self.label_13.setText("")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_13.raise_()
        self.frame_45.raise_()
        self.tableWidget_StockHistory.raise_()
        self.LeftMenuBar.raise_()

        self.retranslateUi(OWNER_STOCKHISTORY)
        QtCore.QMetaObject.connectSlotsByName(OWNER_STOCKHISTORY)

    def retranslateUi(self, OWNER_STOCKHISTORY):
        _translate = QtCore.QCoreApplication.translate
        OWNER_STOCKHISTORY.setWindowTitle(_translate("OWNER_STOCKHISTORY", "Form"))
        item = self.tableWidget_StockHistory.horizontalHeaderItem(0)
        item.setText(_translate("OWNER_STOCKHISTORY", "User ID"))
        item = self.tableWidget_StockHistory.horizontalHeaderItem(1)
        item.setText(_translate("OWNER_STOCKHISTORY", "Username"))
        item = self.tableWidget_StockHistory.horizontalHeaderItem(2)
        item.setText(_translate("OWNER_STOCKHISTORY", "Action  "))
        item = self.tableWidget_StockHistory.horizontalHeaderItem(3)
        item.setText(_translate("OWNER_STOCKHISTORY", "Product Name"))
        item = self.tableWidget_StockHistory.horizontalHeaderItem(4)
        item.setText(_translate("OWNER_STOCKHISTORY", "Old Qty"))
        item = self.tableWidget_StockHistory.horizontalHeaderItem(5)
        item.setText(_translate("OWNER_STOCKHISTORY", "New Qty"))
        item = self.tableWidget_StockHistory.horizontalHeaderItem(6)
        item.setText(_translate("OWNER_STOCKHISTORY", "Updated At"))
        self.comboBox_filterStockHistory.setCurrentText(_translate("OWNER_STOCKHISTORY", "    Filter History"))
        self.comboBox_filterStockHistory.setItemText(0, _translate("OWNER_STOCKHISTORY", "    Filter History"))
        self.comboBox_filterStockHistory.setItemText(1, _translate("OWNER_STOCKHISTORY", "Roof"))
        self.comboBox_filterStockHistory.setItemText(2, _translate("OWNER_STOCKHISTORY", "Spandrel"))
        self.comboBox_filterStockHistory.setItemText(3, _translate("OWNER_STOCKHISTORY", "Gutter"))
        self.comboBox_filterStockHistory.setItemText(4, _translate("OWNER_STOCKHISTORY", "Others"))
        self.lineEdit_OWNER_QuickSearch_StockHistory.setPlaceholderText(_translate("OWNER_STOCKHISTORY", "      Quick Search"))
        self.pushButton_SEARCH_StockHistory.setText(_translate("OWNER_STOCKHISTORY", "Search"))
        self.stockHistoryText.setText(_translate("OWNER_STOCKHISTORY", "Stock History"))
        self.pushButton_OWNER_Delete_Stock.setText(_translate("OWNER_STOCKHISTORY", "Delete Entry"))
        self.stockHistoryText_2.setText(_translate("OWNER_STOCKHISTORY", "Product List"))
        self.pushButton_OWNER_Delete_All.setText(_translate("OWNER_STOCKHISTORY", "Clear All History"))
        self.JJelevate_text_2.setText(_translate("OWNER_STOCKHISTORY", "J&J "))
        self.pushButton_Dashboard.setText(_translate("OWNER_STOCKHISTORY", "  Home   "))
        self.pushButton_Inventory.setText(_translate("OWNER_STOCKHISTORY", "Inventory"))
        self.pushButton_Orders.setText(_translate("OWNER_STOCKHISTORY", " Orders"))
        self.pushButton_Sales.setText(_translate("OWNER_STOCKHISTORY", "  Sales"))
        self.pushButton_Account.setText(_translate("OWNER_STOCKHISTORY", " Account     "))
        self.pushButton_LogOut.setText(_translate("OWNER_STOCKHISTORY", "   Log out"))
        self.pushButton_Stock_History.setText(_translate("OWNER_STOCKHISTORY", "Stock History"))
        self.JJelevate_text_3.setText(_translate("OWNER_STOCKHISTORY", "Elevate"))
